import { Lesson } from './types';

export const levelTwoCommunitiesLesson: Lesson = {
  id: 'MZAIE-P2-M08-L01',
  title: 'AI in South African Communities',
  levelId: 'MZAIE-P2',
  moduleId: 'MZAIE-P2-M08',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Identify a real community problem before deciding whether AI is useful.',
    'Combine prompting, research, data, writing, planning and creativity in one practical workflow.',
    'Design for South African realities such as low data, older Android phones, language diversity and uneven connectivity.',
    'Keep people, privacy, verification and human accountability at the centre of community AI use.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p2m8_b1', type:'objective', variant:'standard', content:'Use the practical AI skills from Level 2 to help solve a real local problem without putting technology before people.' },
    { id:'p2m8_b2', type:'keyPoint', variant:'standard', content:'Start with the problem, not the AI tool. Ask who is affected, what they actually need, what resources they have, and what would count as a useful improvement.' },
    { id:'p2m8_b3', type:'application', variant:'plain', content:'Use the COMMUNITY loop: Clarify the need. Understand the people and context. Map the information and risks. Make a small AI-assisted solution. Use human review. Test in the real setting. Improve from evidence. Take responsibility for the result.' },
    { id:'p2m8_b4', type:'example', variant:'SouthAfricanContext', content:'A TVET college wants to help students find bursary information. AI could help turn verified official information into a simple FAQ, but staff must confirm dates, eligibility rules and links. The final resource should work on a phone and still be useful when data is expensive.' },
    { id:'p2m8_b5', type:'example', variant:'SouthAfricanContext', content:'A church or NGO running a food-support programme could use AI to draft volunteer instructions, translate plain-language notices or organise non-sensitive stock lists. It should not upload beneficiary identity numbers, medical information or confidential case notes into a public AI service.' },
    { id:'p2m8_b6', type:'explanation', variant:'standard', content:'Community problems are often partly digital and partly human. Poor connectivity, language barriers, transport, trust, cost, literacy and access to devices may matter more than the sophistication of the AI. A simple solution that works reliably can be better than a powerful tool that people cannot access.' },
    { id:'p2m8_b7', type:'keyPoint', variant:'standard', content:'Design for the edge first. Prefer short text, low-data pages, clear buttons, simple language, downloadable or offline content where possible, and workflows that still make sense when connectivity disappears.' },
    { id:'p2m8_b8', type:'verification', variant:'standard', content:'Community-facing information can affect real decisions. Verify dates, prices, application rules, safety guidance, legal claims, health information, addresses and contact details from reliable current sources before publication.' },
    { id:'p2m8_b9', type:'ethicsCheck', variant:'standard', content:'Do not use AI to make high-impact decisions about people without proper authority, evidence and human oversight. Be especially careful with children, vulnerable people, employment, money, health, discipline and access to services.' },
    { id:'p2m8_b10', type:'application', variant:'SouthAfricanContext', content:'A small township business could use AI to draft product descriptions, compare weekly sales totals, plan stock questions and create a simple WhatsApp promotion. The owner still checks prices, stock levels, customer privacy and whether the message fits the local audience.' },
    { id:'p2m8_b11', type:'activity', variant:'standard', content:'Choose one real problem from a school, TVET college, NGO, church, small business or community group. Write: 1) the problem, 2) who is affected, 3) one task AI could assist with, 4) one task that must remain human, 5) one privacy or fairness risk, and 6) how the solution could still work with limited data or connectivity.' },
    { id:'p2m8_b12', type:'reflection', variant:'standard', content:'If a solution is technically impressive but too expensive, data-heavy, English-only or difficult to use on an ordinary phone, has it really solved the community problem?' },
    { id:'p2m8_b13', type:'summary', variant:'standard', content:'Level 2 ends with application. Use AI to support real work, but begin with people and evidence. Keep solutions simple, locally relevant, privacy-aware, low-data where possible and subject to human checking. The goal is not to use more AI. The goal is to create a useful, responsible result.' },
  ],
  quiz: [
    { id:'p2m8_q1', question:'What should come first when considering AI for a community problem?', options:['Choosing the newest AI tool.','Defining the real problem, people affected and desired improvement.','Collecting as much personal data as possible.','Making the solution look advanced.'], correctIndex:1, explanation:'Good community AI work starts with the human need and context, not the technology.' },
    { id:'p2m8_q2', question:'Which design choice best fits a low-data community setting?', options:['Large automatic video downloads.','A simple mobile page with short text and offline-friendly information.','A desktop-only dashboard.','A system that fails completely without constant internet.'], correctIndex:1, explanation:'Low-data, mobile and offline-friendly design improves access and resilience.' },
    { id:'p2m8_q3', question:'What is the safest way to publish AI-assisted bursary information?', options:['Publish the AI answer immediately.','Verify dates, eligibility and links against reliable current sources first.','Remove all source references.','Assume old information is still correct.'], correctIndex:1, explanation:'High-impact information should be checked against trustworthy and current evidence.' },
    { id:'p2m8_q4', question:'Which task should receive the strongest human oversight?', options:['Choosing a heading colour.','Deciding whether a vulnerable person should receive an important service.','Reformatting a checklist.','Brainstorming poster titles.'], correctIndex:1, explanation:'High-impact decisions about people require strong human accountability and appropriate authority.' },
    { id:'p2m8_q5', question:'What is the best test of a community AI solution?', options:['Whether it uses the most advanced model.','Whether real users can access it, understand it and gain a useful result safely.','Whether the prompt is very long.','Whether it requires constant high-speed internet.'], correctIndex:1, explanation:'A community solution succeeds when it works for the people and conditions it was designed for.' },
  ],
};
