import { Lesson } from './types';

export const levelFourMeasuringImpactEvidenceLesson: Lesson = {
  id: 'MZAIE-P4-M06-L01',
  title: 'Measuring Impact & Evidence',
  levelId: 'MZAIE-P4',
  moduleId: 'MZAIE-P4-M06',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Define useful outcomes before judging whether an AI-supported solution is successful.',
    'Choose simple evidence that shows whether people are actually helped.',
    'Separate activity, output, outcome and impact when evaluating an AI project.',
    'Use feedback and evidence to improve, pause or stop a solution responsibly.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'DATA_AWARENESS', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p4m6_b1', type:'objective', variant:'standard', content:'Evaluate an AI-supported solution by checking whether it creates a useful, fair and observable improvement for the people it is meant to serve.' },
    { id:'p4m6_b2', type:'explanation', variant:'standard', content:'A project can look busy without making real impact. Many chats, downloads, prompts or generated answers do not prove that people were helped. Impact means something meaningful improved in the real situation.' },
    { id:'p4m6_b3', type:'keyPoint', variant:'standard', content:'Measure the change that matters, not only the activity that is easy to count.' },
    { id:'p4m6_b4', type:'application', variant:'plain', content:'Use the EVIDENCE loop: Expected outcome. Visible signs. Information to collect. Diverse feedback. Errors and harms. Next decision. Continue, improve, pause or stop.' },
    { id:'p4m6_b5', type:'example', variant:'SouthAfricanContext', content:'A study-support app should not only count completed lessons. It should ask whether learners understand more, practise more confidently, make fewer repeated errors, and can explain ideas in their own words.' },
    { id:'p4m6_b6', type:'explanation', variant:'standard', content:'Separate four levels of evidence. Activity is what happened. Output is what was produced. Outcome is what changed for users. Impact is the longer-term benefit or harm in the real setting.' },
    { id:'p4m6_b7', type:'keyPoint', variant:'standard', content:'Good evidence can be simple: before-and-after checks, short interviews, observation, completion records, error logs, user stories, support requests, or a small pilot comparison.' },
    { id:'p4m6_b8', type:'example', variant:'SouthAfricanContext', content:'An NGO uses AI to simplify job-application guidance. Downloads are an activity. Better completed applications are an outcome. More users getting interviews may be impact, but only if other factors are considered honestly.' },
    { id:'p4m6_b9', type:'verification', variant:'standard', content:'Triangulate evidence where possible. Combine numbers with human feedback. A score can show what changed, but user comments often explain why it changed or who was left out.' },
    { id:'p4m6_b10', type:'ethicsCheck', variant:'standard', content:'Ask whether your measurement excludes quieter users, people without data, people with disabilities, non-English speakers or those who stopped using the tool because it failed them.' },
    { id:'p4m6_b11', type:'application', variant:'SouthAfricanContext', content:'For a community AI pilot, choose three measures: one usefulness measure, one access measure and one risk measure. For example: task completion, low-data usability and number of incorrect or confusing answers reported.' },
    { id:'p4m6_b12', type:'activity', variant:'standard', content:'Choose one AI-supported project. Write: 1) the intended outcome, 2) one activity measure, 3) one output measure, 4) one outcome measure, 5) one possible harm, 6) one feedback question, 7) how you will know who was excluded, and 8) the decision rule for improving, pausing or stopping.' },
    { id:'p4m6_b13', type:'reflection', variant:'standard', content:'What evidence would convince you that the solution is not working, even if you personally like the idea?' },
    { id:'p4m6_b14', type:'summary', variant:'standard', content:'Impact measurement asks whether a solution genuinely helps people. Define outcomes first, collect simple evidence, listen to users, watch for exclusion and harm, and use the evidence to improve, pause or stop responsibly.' },
  ],
  quiz: [
    { id:'p4m6_q1', question:'Why are usage numbers alone not enough to prove impact?', options:['Because many uses do not prove people were helped.','Because numbers are never useful.','Because impact cannot be observed.','Because AI projects should not be measured.'], correctIndex:0, explanation:'Activity can be high while real outcomes remain weak or harmful.' },
    { id:'p4m6_q2', question:'What is an outcome?', options:['The number of buttons clicked.','A meaningful change for users or the real situation.','The title of a project.','The AI model used.'], correctIndex:1, explanation:'An outcome is the change the project is meant to create.' },
    { id:'p4m6_q3', question:'What is the strongest evidence approach?', options:['Use only one score.','Combine simple numbers with user feedback and observation.','Ignore negative feedback.','Ask AI to rate the project only.'], correctIndex:1, explanation:'Mixed evidence helps explain both what changed and why.' },
    { id:'p4m6_q4', question:'What should happen if evidence shows the tool confuses or harms users?', options:['Keep scaling because the idea is good.','Improve, pause or stop the solution depending on the risk.','Hide the evidence.','Collect more private data from users.'], correctIndex:1, explanation:'Responsible evaluation uses evidence to make decisions, including stopping when needed.' },
    { id:'p4m6_q5', question:'Why check who is excluded from the evidence?', options:['Because missing voices can hide unfairness or access barriers.','Because excluded users do not matter.','Because all users have the same devices and language.','Because feedback should only come from confident users.'], correctIndex:0, explanation:'People left out of measurement may be the people most affected by the design.' },
  ],
};
