import { Lesson } from './types';

export const levelFourEducationNgosChurchesLesson: Lesson = {
  id: 'MZAIE-P4-M03-L01',
  title: 'AI for Education, NGOs & Churches',
  levelId: 'MZAIE-P4',
  moduleId: 'MZAIE-P4-M03',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Design AI-supported services for schools, NGOs, churches and community organisations responsibly.',
    'Match AI use to a real support need without replacing trusted human relationships.',
    'Protect children, vulnerable people, private information and community dignity.',
    'Plan simple offline and low-data workflows that can be tested before wider rollout.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'BASIC_PRIVACY', 'HUMAN_JUDGEMENT', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p4m3_b1', type:'objective', variant:'standard', content:'Use AI carefully in community-serving institutions by supporting real people, reducing practical barriers and keeping trusted human care, safeguarding and accountability in place.' },
    { id:'p4m3_b2', type:'explanation', variant:'standard', content:'Schools, NGOs and churches often hold deep trust. They also serve people who may have limited data, low digital confidence, language barriers, trauma, poverty or urgent needs. AI must strengthen support, not create distance, confusion or hidden risk.' },
    { id:'p4m3_b3', type:'keyPoint', variant:'standard', content:'In community settings, the first design question is not “Can AI do this?” It is “Would AI make the support clearer, safer, cheaper, faster or more reachable without weakening human responsibility?”' },
    { id:'p4m3_b4', type:'application', variant:'plain', content:'Use the CARE workflow: Clarify the service need. Assess risks and safeguarding. Reduce data collection. Explain in plain language. Keep human referral and review. This prevents AI from becoming a careless shortcut.' },
    { id:'p4m3_b5', type:'example', variant:'SouthAfricanContext', content:'A church youth group wants to help matric learners study. A responsible AI tool can organise revision questions, explain concepts simply and suggest practice plans. It should not pretend to be a counsellor, diagnose learners or replace adult support where safeguarding is needed.' },
    { id:'p4m3_b6', type:'explanation', variant:'standard', content:'AI is useful for repeated information tasks, plain-language explanations, translation support, checklists, draft messages, lesson practice and referral guidance. It is risky when it makes high-impact decisions, handles sensitive stories without safeguards or gives advice beyond its limits.' },
    { id:'p4m3_b7', type:'keyPoint', variant:'standard', content:'Low-data and offline design matter in community organisations. A printable checklist, saved guide, offline lesson or simple phone-friendly form may serve people better than a live chatbot that fails when signal or data runs out.' },
    { id:'p4m3_b8', type:'example', variant:'SouthAfricanContext', content:'An NGO helps people prepare job applications. AI can help draft a CV summary, simplify requirements and practise interview questions. A human still checks accuracy, confirms eligibility and protects personal information before documents are shared.' },
    { id:'p4m3_b9', type:'verification', variant:'standard', content:'Before launch, test with a small group of actual users and one responsible staff member. Check whether people understand the tool, whether the answers are useful, whether private information is exposed and whether the handover to a human works.' },
    { id:'p4m3_b10', type:'ethicsCheck', variant:'standard', content:'When children, vulnerable adults or people in crisis are involved, the design must include consent, safeguarding, clear limits, referral pathways and a responsible adult or organisation. AI must never become the hidden authority in sensitive support.' },
    { id:'p4m3_b11', type:'application', variant:'SouthAfricanContext', content:'A school, NGO or church can begin with a narrow pilot: one topic, one audience, one trusted facilitator, one offline fallback and one simple feedback form. This is safer than launching a broad tool before the risks are understood.' },
    { id:'p4m3_b12', type:'activity', variant:'standard', content:'Choose one community-serving use case. Write: 1) the group served, 2) the support need, 3) what AI may help with, 4) what AI must not do, 5) what information should not be collected, 6) who reviews output, 7) the offline fallback, and 8) how feedback will be captured.' },
    { id:'p4m3_b13', type:'reflection', variant:'standard', content:'Would the people receiving support feel more respected, safer and clearer after using this AI-supported service? If not, what must change?' },
    { id:'p4m3_b14', type:'summary', variant:'standard', content:'AI can support education, NGOs, churches and community organisations when it is narrow, plain, low-data, privacy-aware and governed by responsible people. The goal is stronger human support, not automated care without accountability.' },
  ],
  quiz: [
    { id:'p4m3_q1', question:'What is the best role for AI in schools, NGOs and churches?', options:['Replace trusted people completely.','Support clear, safe, limited tasks while humans remain responsible.','Collect private stories for future use.','Make final decisions about vulnerable people.'], correctIndex:1, explanation:'AI should support useful tasks while human responsibility remains clear.' },
    { id:'p4m3_q2', question:'Why is offline or low-data design important in community settings?', options:['Because many users may have limited connectivity, data or devices.','Because online tools are always unsafe.','Because AI cannot use the internet.','Because simple tools never need testing.'], correctIndex:0, explanation:'Access conditions shape whether people can actually use the support.' },
    { id:'p4m3_q3', question:'Which use is highest risk?', options:['Creating revision questions.','Simplifying a public information leaflet.','Making unsupported crisis or safeguarding decisions.','Drafting a meeting reminder.'], correctIndex:2, explanation:'Sensitive or high-impact situations need trained human oversight and referral.' },
    { id:'p4m3_q4', question:'What should a small pilot include?', options:['A narrow audience, responsible facilitator, offline fallback and feedback capture.','Every possible feature from the start.','No human review so the test is faster.','Private data collection without explanation.'], correctIndex:0, explanation:'A narrow controlled pilot reveals value and risk before wider rollout.' },
    { id:'p4m3_q5', question:'What protects dignity in a community AI service?', options:['Clear limits, privacy protection, human review and respectful language.','Making the tool sound powerful.','Hiding when AI is used.','Forcing users to share sensitive information.'], correctIndex:0, explanation:'Dignity requires transparency, restraint, privacy and accountable support.' },
  ],
};
