import { Lesson } from './types';

export const levelTwoCreativityLesson: Lesson = {
  id: 'MZAIE-P2-M07-L01',
  title: 'AI for Creativity & Content',
  levelId: 'MZAIE-P2',
  moduleId: 'MZAIE-P2-M07',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Use AI to generate and develop ideas without surrendering your own creative judgement.',
    'Create stronger stories, presentations and visual concepts through a repeatable creative workflow.',
    'Protect originality, cultural sensitivity, privacy and attribution when using AI-generated content.',
    'Evaluate AI-created material for quality, relevance, bias and factual accuracy before publishing or presenting it.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id: 'p2m7_b1', type: 'objective', variant: 'standard', content: 'Learn to use AI as a creative partner for ideas, stories, presentations and visual concepts while keeping originality, meaning and final judgement in human hands.' },
    { id: 'p2m7_b2', type: 'explanation', variant: 'standard', content: 'AI can help you brainstorm options, explore angles, organise a presentation, suggest titles, develop characters, create outlines or describe visual concepts. It is most useful when it expands your choices rather than replacing your own ideas.' },
    { id: 'p2m7_b3', type: 'keyPoint', variant: 'standard', content: 'Creative quality does not come from accepting the first AI output. Good work usually requires selecting, combining, rejecting, refining and rewriting.' },
    { id: 'p2m7_b4', type: 'application', variant: 'plain', content: 'Use the CREATE loop: Clarify the purpose. Request several possibilities. Evaluate what fits. Adapt it in your own voice. Test for truth, tone and sensitivity. Edit until the final result is genuinely yours.' },
    { id: 'p2m7_b5', type: 'example', variant: 'SouthAfricanContext', content: 'A learner preparing a Heritage Day presentation could ask AI for five possible story angles about local food, language, music or family traditions. The learner should choose one angle, add real local knowledge, verify historical claims and avoid turning cultures into stereotypes.' },
    { id: 'p2m7_b6', type: 'explanation', variant: 'standard', content: 'For presentations, AI can help structure a beginning, middle and end, suggest slide headings, shorten dense text or propose visual ideas. But every claim, statistic and quotation still needs checking.' },
    { id: 'p2m7_b7', type: 'example', variant: 'SouthAfricanContext', content: 'A small community organisation could ask AI for three poster concepts for a youth clean-up campaign. The team should then choose the concept that fits the community, use correct local details, remove clichés and make sure images or wording do not misrepresent people.' },
    { id: 'p2m7_b8', type: 'ethicsCheck', variant: 'standard', content: 'Do not present AI-generated work as fully human-made when disclosure is required. Respect copyright, school or workplace rules, and the rights of other creators. Avoid uploading private photos, confidential material or personal information merely to create content.' },
    { id: 'p2m7_b9', type: 'verification', variant: 'standard', content: 'Creative content can still contain invented facts, false quotations, misleading images or biased assumptions. Check factual claims and ask whether the content is fair, respectful and suitable for the audience.' },
    { id: 'p2m7_b10', type: 'application', variant: 'SouthAfricanContext', content: 'Local language, humour and cultural references can make content more relevant, but AI may misunderstand them. Keep human review especially strong when working with multilingual, cultural or community-specific material.' },
    { id: 'p2m7_b11', type: 'activity', variant: 'standard', content: 'Choose one real creative task. Ask AI for three different concepts, not one finished answer. Select the strongest parts from at least two options, add your own idea, then produce a final version that you could explain and defend without the AI.' },
    { id: 'p2m7_b12', type: 'reflection', variant: 'standard', content: 'If AI makes content faster but also makes everyone sound or look similar, what do creators risk losing? Which parts of your own voice, community or experience should never be outsourced?' },
    { id: 'p2m7_b13', type: 'keyPoint', variant: 'standard', content: 'Originality is not only about whether an idea has appeared before. It is also about your choices, perspective, judgement, lived experience and the meaning you add.' },
    { id: 'p2m7_b14', type: 'summary', variant: 'standard', content: 'Use AI to expand possibilities, not to flatten creativity. Generate options, choose critically, add human perspective, verify facts, respect rights and culture, and take responsibility for the final content.' },
  ],
  quiz: [
    { id: 'p2m7_q1', question: 'What is the strongest way to use AI for a creative task?', options: ['Accept the first output unchanged.', 'Generate several options, evaluate them, then adapt the best ideas in your own way.', 'Ask AI to copy a famous creator exactly.', 'Remove all local context so the result sounds generic.'], correctIndex: 1, explanation: 'Creative quality improves when AI expands options and the human selects, adapts and adds meaning.' },
    { id: 'p2m7_q2', question: 'Why should a learner verify facts in an AI-assisted presentation?', options: ['Creative work cannot contain facts.', 'AI can invent statistics, quotations or historical details.', 'Verification is only needed for mathematics.', 'Because every slide must have a reference list.'], correctIndex: 1, explanation: 'AI-generated creative content can still contain factual errors or invented evidence.' },
    { id: 'p2m7_q3', question: 'Which action best protects originality?', options: ['Use AI to create the full piece and submit it unchanged.', 'Use several AI ideas as raw material, then add your own choices, experience and voice.', 'Ask AI to imitate a living creator exactly.', 'Choose the longest answer automatically.'], correctIndex: 1, explanation: 'Originality grows from human selection, perspective, adaptation and authorship.' },
    { id: 'p2m7_q4', question: 'What should you do if AI produces a cultural stereotype in a community poster?', options: ['Keep it because AI generated it.', 'Remove or revise it and use accurate, respectful local knowledge.', 'Make it more exaggerated so it is memorable.', 'Publish it before anyone reviews it.'], correctIndex: 1, explanation: 'Human review must correct stereotypes and protect cultural accuracy and dignity.' },
    { id: 'p2m7_q5', question: 'Who remains responsible for the final AI-assisted creative work?', options: ['The AI system only.', 'The person or team that chooses to publish, submit or present it.', 'Nobody if AI was used.', 'The internet provider.'], correctIndex: 1, explanation: 'The human creator or team remains responsible for the final choices, accuracy, rights and impact.' },
  ],
};
