import { Lesson } from './types';

export const levelThreeTestingBiasLesson: Lesson = {
  id: 'MZAIE-P3-M06-L01',
  title: 'Testing, Evaluation & Bias Checks',
  levelId: 'MZAIE-P3',
  moduleId: 'MZAIE-P3-M06',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Design useful test cases before trusting an AI prototype.',
    'Identify hallucinations, weak outputs, edge cases and failure patterns.',
    'Check for unfair outcomes, language bias and accessibility problems.',
    'Use clear pass/fail criteria to decide whether a prototype is ready for wider use.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p3m6_b1', type:'objective', variant:'standard', content:'Move from “it works on my example” to disciplined testing. A responsible builder tries to make the prototype fail before real users depend on it.' },
    { id:'p3m6_b2', type:'explanation', variant:'standard', content:'Testing asks whether the prototype is accurate, useful, safe, understandable and fair across different users and situations. Evaluation turns those observations into a decision: pass, improve or do not deploy.' },
    { id:'p3m6_b3', type:'keyPoint', variant:'standard', content:'A successful demo is not evidence of a reliable product. Test normal cases, difficult cases, unusual cases and known failure conditions.' },
    { id:'p3m6_b4', type:'application', variant:'plain', content:'Use the TEST loop: Target the expected behaviour. Exercise normal and edge cases. Spot errors, hallucinations, bias and confusing outputs. Track results against clear criteria. Then repair and retest.' },
    { id:'p3m6_b5', type:'example', variant:'SouthAfricanContext', content:'A bursary-information assistant may work well for a standard English question but fail when a learner uses informal wording, Afrikaans, isiXhosa, a misspelled institution name or an older deadline. A useful test set must include these realistic variations.' },
    { id:'p3m6_b6', type:'explanation', variant:'standard', content:'Create at least four kinds of test cases: expected cases that should succeed, boundary cases that stretch the system, failure cases where the system should refuse or hand over, and adversarial cases that try to expose unsafe or misleading behaviour.' },
    { id:'p3m6_b7', type:'verification', variant:'standard', content:'Check factual outputs against trusted sources. If the prototype invents a source, confuses a date, changes a rule or gives unsupported certainty, record it as a failure even if the answer sounds confident.' },
    { id:'p3m6_b8', type:'keyPoint', variant:'standard', content:'Hallucination risk matters most when users may act on the answer. The correct response to uncertainty is not confident guessing. The system should say what it knows, what it cannot verify and when a human or official source is required.' },
    { id:'p3m6_b9', type:'ethicsCheck', variant:'standard', content:'Bias testing asks whether different groups receive systematically weaker, less respectful or less useful outcomes. Test language, literacy level, device constraints, location, names, disability-related needs and other context relevant to the intended users.' },
    { id:'p3m6_b10', type:'example', variant:'SouthAfricanContext', content:'A job-application helper should not produce polished outputs only for formal English users. Test it with plain English, common South African names, varied education histories, code-switching and lower-literacy prompts. The goal is not identical wording but comparable usefulness and dignity.' },
    { id:'p3m6_b11', type:'application', variant:'standard', content:'Write measurable pass/fail criteria before testing. Examples: all critical dates must match the approved source, the assistant must refuse to invent missing information, every critical action must have a human escalation path, and key screens must remain usable on an ordinary phone.' },
    { id:'p3m6_b12', type:'explanation', variant:'standard', content:'User testing adds evidence the builder cannot generate alone. Ask a small group of representative users to complete realistic tasks without coaching. Watch where they hesitate, misunderstand, abandon the task or trust the system too much.' },
    { id:'p3m6_b13', type:'keyPoint', variant:'standard', content:'A prototype is not ready when critical failures remain unresolved, when test coverage is too narrow, when important claims cannot be verified, when some user groups are consistently disadvantaged, or when there is no safe fallback for failure.' },
    { id:'p3m6_b14', type:'activity', variant:'standard', content:'Choose one Level 3 prototype idea. Create an eight-case mini test set: 2 normal cases, 2 edge cases, 1 known failure case, 1 language/accessibility case, 1 fairness/bias case and 1 misinformation or hallucination case. For each, write the expected result and whether the observed result is PASS, IMPROVE or FAIL.' },
    { id:'p3m6_b15', type:'reflection', variant:'standard', content:'Which failure would cause the most harm if a real user trusted your prototype? What test would reveal that failure before deployment?' },
    { id:'p3m6_b16', type:'summary', variant:'standard', content:'Responsible AI builders do not test only for success. They search for failure, verify important claims, compare outcomes across users, test realistic South African language and access conditions, define pass/fail criteria and refuse to deploy when critical risks remain unresolved.' },
  ],
  quiz: [
    { id:'p3m6_q1', question:'Why should a builder test edge cases as well as normal cases?', options:['To make the test set look larger.','Because real users and conditions often differ from the ideal example.','Because normal cases are never useful.','Only to test internet speed.'], correctIndex:1, explanation:'Edge cases reveal failures that a polished demo or standard example may hide.' },
    { id:'p3m6_q2', question:'What should happen when an AI prototype cannot verify an important fact?', options:['It should guess confidently.','It should hide the uncertainty.','It should show uncertainty and direct the user to verification or human review where needed.','It should invent a source.'], correctIndex:2, explanation:'Responsible systems make uncertainty visible instead of converting it into false confidence.' },
    { id:'p3m6_q3', question:'Which is the strongest bias test?', options:['Test only with the builder’s own wording.','Compare usefulness across realistic language, literacy and user contexts.','Check only whether the interface colour looks neutral.','Ask the AI whether it is biased.'], correctIndex:1, explanation:'Bias testing requires comparing actual outcomes across relevant user contexts.' },
    { id:'p3m6_q4', question:'When should a prototype be marked not ready to deploy?', options:['Whenever one minor spelling issue appears.','When critical failures, unfair outcomes or unsafe fallback gaps remain unresolved.','Only when the design is unattractive.','Only when no video resource exists.'], correctIndex:1, explanation:'Critical reliability, fairness and safety failures are deployment blockers.' },
    { id:'p3m6_q5', question:'What is the purpose of pass/fail criteria?', options:['To decide in advance what acceptable behaviour looks like.','To guarantee the AI will never fail.','To replace user testing.','To make every output identical.'], correctIndex:0, explanation:'Clear criteria make evaluation more consistent and prevent moving the goalposts after seeing the results.' },
  ],
};
