import { Lesson } from './types';

export const levelThreePrivacySafetyLesson: Lesson = {
  id: 'MZAIE-P3-M07-L01',
  title: 'Privacy, Safety & Responsible Deployment',
  levelId: 'MZAIE-P3',
  moduleId: 'MZAIE-P3-M07',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Reduce privacy and safety risks before an AI prototype reaches real users.',
    'Apply data minimisation, consent, access control and human oversight.',
    'Plan safe pilot boundaries, fallback, revocation and recovery.',
    'Decide whether a prototype is responsible enough to deploy.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p3m7_b1', type:'objective', variant:'standard', content:'A prototype that works technically can still be unsafe. Responsible deployment means protecting people, limiting data, controlling access and preparing for failure before real users depend on the system.' },
    { id:'p3m7_b2', type:'explanation', variant:'standard', content:'Start with data minimisation: collect, store and share only what the task genuinely requires. Names, identity numbers, contact details, health information, school records and other personal information should never be collected simply because the technology allows it.' },
    { id:'p3m7_b3', type:'keyPoint', variant:'standard', content:'Ask four questions about every data field: Why do we need it? Who can see it? Where is it stored? When can it be deleted? If the first answer is weak, do not collect the data.' },
    { id:'p3m7_b4', type:'application', variant:'plain', content:'Use the SAFE deployment check: Scope the pilot. Ask for informed consent where needed. Fence access and sensitive data. Establish human oversight, fallback and an exit plan.' },
    { id:'p3m7_b5', type:'example', variant:'SouthAfricanContext', content:'A community learning assistant can help learners practise without storing their full names, ID numbers or home addresses. A simple local learner nickname may be enough. The safest useful dataset is often smaller than the easiest dataset to collect.' },
    { id:'p3m7_b6', type:'explanation', variant:'standard', content:'Consent must be meaningful. People should understand what the prototype does, what information it uses, what its limits are and how to stop participating. Where children or vulnerable people are involved, safeguarding and appropriate adult oversight become especially important.' },
    { id:'p3m7_b7', type:'keyPoint', variant:'standard', content:'Separate user access from owner control. A local learner or administrator setting should not be the same mechanism the product owner uses to revoke a pilot, close access or respond to misuse.' },
    { id:'p3m7_b8', type:'explanation', variant:'standard', content:'Local and offline storage reduces network dependence, but it does not remove privacy risk. A lost, shared or reset phone can expose or erase locally stored information. Decide what is stored, whether it is sensitive, how long it remains and what recovery is possible.' },
    { id:'p3m7_b9', type:'ethicsCheck', variant:'standard', content:'Human oversight must be real. Identify who reviews uncertain or high-impact outputs, who can correct harmful content, who responds to complaints and which decisions the AI is never allowed to make alone.' },
    { id:'p3m7_b10', type:'example', variant:'SouthAfricanContext', content:'A worker-rights information prototype may explain general information, but it should not silently make legal decisions for a worker. It should identify uncertainty, point to trusted sources and provide a human escalation route when the consequences are serious.' },
    { id:'p3m7_b11', type:'application', variant:'standard', content:'Pilot narrowly before wider release. Define who may use the prototype, for how long, what evidence you will collect, which failures stop the pilot, and how access can be revoked without destroying legitimate user data.' },
    { id:'p3m7_b12', type:'explanation', variant:'standard', content:'Prepare rollback and recovery before launch. Keep a known-good version, know how to disable a broken feature or close a pilot, avoid irreversible data changes where possible, and document what the user should do when the service or network is unavailable.' },
    { id:'p3m7_b13', type:'keyPoint', variant:'standard', content:'Do not deploy when critical privacy questions are unanswered, sensitive data is collected without a clear need, access cannot be controlled, vulnerable users lack safeguards, high-impact outputs lack human review, or there is no practical way to stop a harmful pilot.' },
    { id:'p3m7_b14', type:'activity', variant:'standard', content:'Create a one-page deployment gate for your Level 3 prototype. Record: intended users, minimum data required, data you refuse to collect, consent needs, access controls, human reviewer, offline/local-storage risk, three stop-pilot conditions, revoke/rollback method and recovery plan. Mark each item READY, NEEDS WORK or BLOCKED.' },
    { id:'p3m7_b15', type:'reflection', variant:'standard', content:'If your prototype were placed in the hands of a learner, worker, parent or community volunteer tomorrow, what is the single most important risk you would want controlled before they use it?' },
    { id:'p3m7_b16', type:'summary', variant:'standard', content:'Responsible deployment protects people before scale. Minimise data, make consent meaningful, control access, protect vulnerable users, plan for local-storage risks, keep humans responsible for high-impact decisions, pilot narrowly and maintain a real revoke, rollback and recovery path.' },
  ],
  quiz: [
    { id:'p3m7_q1', question:'What does data minimisation mean?', options:['Collect everything in case it becomes useful later.','Collect only information genuinely required for the task.','Store all data permanently.','Move every field to the cloud.'], correctIndex:1, explanation:'Data minimisation reduces exposure by limiting collection to information that has a clear purpose.' },
    { id:'p3m7_q2', question:'Why should owner access control be separate from a user’s local settings?', options:['So the owner can control or revoke the pilot without relying on or changing the user’s local controls.','To make every user an owner.','So local data must always be deleted.','Only to change colours.'], correctIndex:0, explanation:'Separate owner control supports safe revocation while preserving appropriate local user settings and data.' },
    { id:'p3m7_q3', question:'Which statement about offline local storage is correct?', options:['It has no privacy risk.','It removes the need for access controls.','It can reduce network dependence but still creates loss, sharing and device-access risks.','It automatically backs itself up.'], correctIndex:2, explanation:'Offline storage changes the risk profile but does not eliminate privacy or recovery concerns.' },
    { id:'p3m7_q4', question:'When should a pilot be blocked from deployment?', options:['When critical privacy, safeguarding or human-oversight gaps remain unresolved.','Whenever the prototype works offline.','When the lesson has a video link.','Only when every user dislikes the colours.'], correctIndex:0, explanation:'Critical safety and governance gaps are deployment blockers even when the technology works.' },
    { id:'p3m7_q5', question:'What belongs in a responsible rollback plan?', options:['A way to stop or revert a harmful release and recover safely.','A promise that nothing will ever fail.','A larger marketing campaign.','A requirement to keep every version live forever.'], correctIndex:0, explanation:'Rollback and recovery planning provides a practical response when a deployment causes problems.' },
  ],
};
