import { Lesson } from './types';

export const levelFourPublicServiceCivicInnovationLesson: Lesson = {
  id: 'MZAIE-P4-M05-L01',
  title: 'Public Service & Civic Innovation',
  levelId: 'MZAIE-P4',
  moduleId: 'MZAIE-P4-M05',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Identify public-service and civic-access problems where AI may improve clarity, reach or responsiveness.',
    'Design AI-supported civic tools that protect rights, fairness, privacy and human accountability.',
    'Separate public information support from official decisions, legal advice or rights-affecting actions.',
    'Plan low-data and offline-friendly civic support that can be tested safely with real users.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p4m5_b1', type:'objective', variant:'standard', content:'Use AI responsibly to improve access to public information, civic participation and community-facing services without replacing official accountability or people’s rights.' },
    { id:'p4m5_b2', type:'explanation', variant:'standard', content:'Public-service innovation must be handled carefully because it can affect rights, access, fairness and trust. AI can simplify information and guide next steps, but it must not secretly make official decisions or invent policy requirements.' },
    { id:'p4m5_b3', type:'keyPoint', variant:'standard', content:'In civic settings, AI should make verified information easier to understand. It should not become an unaccountable gatekeeper between people and the services they need.' },
    { id:'p4m5_b4', type:'application', variant:'plain', content:'Use the CIVIC loop: Check the official source. Identify the user need. Verify the rule or process. Improve plain-language access. Clarify limits. Keep human escalation available.' },
    { id:'p4m5_b5', type:'example', variant:'SouthAfricanContext', content:'A community group wants to help residents understand municipal service notices. A responsible tool can summarise verified notices in plain language and local languages. It must show the source, date and limits, and direct users to the official channel for disputes or urgent issues.' },
    { id:'p4m5_b6', type:'explanation', variant:'standard', content:'Public information often changes. Deadlines, forms, office hours, eligibility rules and contact details can become outdated. AI-supported civic tools need source dates, review routines and a clear warning when information may be stale.' },
    { id:'p4m5_b7', type:'keyPoint', variant:'standard', content:'A civic AI tool must protect people who already face barriers: low literacy, disability, language exclusion, lack of data, no email address, shared phones or fear of institutions.' },
    { id:'p4m5_b8', type:'example', variant:'SouthAfricanContext', content:'A clinic information assistant may explain what documents to bring and how queues work. It must not diagnose illness, promise treatment priority, expose patient details or contradict official medical guidance.' },
    { id:'p4m5_b9', type:'verification', variant:'standard', content:'Before using a civic AI workflow, verify every answer against an official or trusted source. Test it with real users and check whether they understand the limits, the source and the next action.' },
    { id:'p4m5_b10', type:'ethicsCheck', variant:'standard', content:'Ask whether the tool could wrongly deny access, mislead people about rights, favour connected users, expose private information, or make official processes harder to challenge.' },
    { id:'p4m5_b11', type:'application', variant:'SouthAfricanContext', content:'A ward councillor office, advice desk or community organisation can start with a narrow offline-friendly guide: one service area, verified source text, plain-language steps, a referral pathway and a feedback form for errors.' },
    { id:'p4m5_b12', type:'activity', variant:'standard', content:'Choose one civic service problem. Write: 1) who needs help, 2) the official source, 3) what users find confusing, 4) what AI may simplify, 5) what AI must not decide, 6) privacy risks, 7) the human escalation route, and 8) how updates will be checked.' },
    { id:'p4m5_b13', type:'reflection', variant:'standard', content:'Would this tool make public access more equal, or would it mainly help people who already have data, confidence and digital skills?' },
    { id:'p4m5_b14', type:'summary', variant:'standard', content:'AI can support public service and civic innovation when it uses verified sources, plain language, clear limits, privacy protection, human escalation and offline-friendly access. Civic AI must strengthen rights and accountability, not weaken them.' },
  ],
  quiz: [
    { id:'p4m5_q1', question:'What is the safest role for AI in public-service information?', options:['Make official decisions secretly.','Simplify verified information and guide users to clear next steps.','Replace appeals and human escalation.','Invent missing rules when sources are unclear.'], correctIndex:1, explanation:'AI should improve access to verified information, not replace official accountability.' },
    { id:'p4m5_q2', question:'Why must civic AI show source limits or review dates?', options:['Because public information can change and outdated guidance can harm people.','Because dates make the screen look formal.','Because users never check sources.','Because AI output is always current.'], correctIndex:0, explanation:'Changing rules and deadlines require visible source control and review.' },
    { id:'p4m5_q3', question:'Which civic use is highest risk?', options:['Summarising a verified notice.','Explaining what documents to bring.','Wrongly telling someone they do not qualify for a service.','Translating public office hours.'], correctIndex:2, explanation:'Rights-affecting guidance can deny access if it is wrong or unreviewed.' },
    { id:'p4m5_q4', question:'What should a civic AI tool protect?', options:['Only speed.','Rights, fairness, privacy, access and human accountability.','The institution from all questions.','The AI system from correction.'], correctIndex:1, explanation:'Public-service tools must protect people and accountable processes.' },
    { id:'p4m5_q5', question:'What is a good first civic pilot?', options:['All public services at once.','One narrow service area with verified sources, plain steps and a referral route.','A chatbot with no human contact option.','A tool that collects private data before helping.'], correctIndex:1, explanation:'A narrow verified pilot is safer and easier to test than broad automation.' },
  ],
};
