import { Lesson } from './types';

export const levelThreeAssistantsWorkflowsLesson: Lesson = {
  id: 'MZAIE-P3-M02-L01',
  title: 'Designing AI Assistants & Workflows',
  levelId: 'MZAIE-P3',
  moduleId: 'MZAIE-P3-M02',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Map an AI assistant or workflow with clear inputs, steps, outputs and human checkpoints.',
    'Separate what the AI may do from what must remain a human responsibility.',
    'Design a workflow that still makes sense on ordinary phones and under weak connectivity.',
    'Test whether the proposed assistant reduces effort without creating new privacy, accuracy or access risks.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p3m2_b1', type:'objective', variant:'standard', content:'Turn a defined problem into a practical assistant or workflow by deciding what information goes in, what steps happen, what comes out and where a human must check or decide.' },
    { id:'p3m2_b2', type:'explanation', variant:'standard', content:'An AI assistant is not just a chat box. It is a designed process. A useful design names the user, the trigger, the inputs, the sequence of tasks, the expected output, the limits and the point where a human reviews the result.' },
    { id:'p3m2_b3', type:'keyPoint', variant:'standard', content:'A workflow is only as strong as its hand-offs. Define exactly when the AI acts, when a person acts, what evidence is checked, and what happens when the AI is uncertain or offline.' },
    { id:'p3m2_b4', type:'application', variant:'plain', content:'Use the FLOW loop: Frame the user need. List the inputs. Order the steps. Watch for risk and uncertainty. Output a useful result. Locate the human checkpoint. Test the workflow from start to finish.' },
    { id:'p3m2_b5', type:'example', variant:'SouthAfricanContext', content:'A TVET student support office receives repeated requests for bursary guidance. The workflow could start with a learner choosing a bursary topic, retrieve only verified current information, produce a short plain-language summary, show the official source link, and send unusual cases to a staff member. The AI should not decide whether the learner qualifies.' },
    { id:'p3m2_b6', type:'explanation', variant:'standard', content:'Good inputs are specific and limited. If the assistant needs only a topic and province, do not collect a full identity number, home address or private learner record. Every extra input creates cost, complexity and privacy risk.' },
    { id:'p3m2_b7', type:'keyPoint', variant:'standard', content:'Design for failure, not only success. Decide what the assistant should do when the internet drops, a source is missing, the request is unclear, the answer may be outdated, or the task requires authority the system does not have.' },
    { id:'p3m2_b8', type:'example', variant:'SouthAfricanContext', content:'A church volunteer coordinator could use a simple assistant to turn a list of non-sensitive tasks into a weekly duty checklist and draft a WhatsApp reminder. If connectivity fails, the last saved duty list should still be visible. Sensitive pastoral notes should never be part of this workflow.' },
    { id:'p3m2_b9', type:'verification', variant:'standard', content:'For information-heavy workflows, include a verification step before the final output. The workflow should identify the source, check whether it is current, and distinguish between verified facts and generated wording.' },
    { id:'p3m2_b10', type:'ethicsCheck', variant:'standard', content:'Never hide a high-impact decision inside an automated workflow. Decisions involving employment, discipline, money, health, legal rights, learner admission or access to essential services require appropriate human authority and accountability.' },
    { id:'p3m2_b11', type:'application', variant:'SouthAfricanContext', content:'A small community business could design an assistant that takes a short product description and current price, drafts a WhatsApp promotion, checks that no unsupported claim was added, and then waits for the owner to approve before sending. The final send remains human-controlled.' },
    { id:'p3m2_b12', type:'activity', variant:'standard', content:'Choose one problem from Module 3.1 and map a seven-part workflow: 1) user, 2) trigger, 3) minimum inputs, 4) AI-assisted steps, 5) human steps, 6) output, and 7) failure or offline fallback. Then mark one privacy risk and one verification checkpoint.' },
    { id:'p3m2_b13', type:'reflection', variant:'standard', content:'If your assistant produces a polished answer but the user cannot tell where the information came from, who checks it or what to do when it is wrong, is the workflow actually trustworthy?' },
    { id:'p3m2_b14', type:'summary', variant:'standard', content:'Design AI assistants as controlled workflows, not magic boxes. Use the minimum necessary inputs, make the sequence visible, build in source checks, preserve human authority, plan for weak connectivity and test every hand-off before real use.' },
  ],
  quiz: [
    { id:'p3m2_q1', question:'What is the strongest way to think about an AI assistant?', options:['As a chat box that answers anything.','As a designed workflow with inputs, steps, outputs and human checkpoints.','As a replacement for every human task.','As a tool that should collect as much data as possible.'], correctIndex:1, explanation:'A useful assistant is a controlled process with clear responsibilities and boundaries.' },
    { id:'p3m2_q2', question:'Why should a workflow collect only the minimum necessary inputs?', options:['To make the screen look empty.','To reduce privacy risk, cost and unnecessary complexity.','Because AI cannot process detailed information.','To avoid testing the workflow.'], correctIndex:1, explanation:'Unnecessary data increases privacy exposure and complexity without improving the task.' },
    { id:'p3m2_q3', question:'What should happen when an AI workflow reaches a high-impact decision about a person?', options:['The AI should decide automatically.','The workflow should route the decision to an appropriately authorised human.','The user should accept the first answer.','The system should hide how the decision was made.'], correctIndex:1, explanation:'High-impact decisions require human authority, oversight and accountability.' },
    { id:'p3m2_q4', question:'Which design best supports weak or intermittent connectivity?', options:['A workflow that fails completely without constant internet.','A workflow with a clear offline or saved-information fallback where possible.','A workflow that automatically streams large videos.','A desktop-only workflow for phone users.'], correctIndex:1, explanation:'Resilient workflows preserve useful functions or guidance when connectivity is weak.' },
    { id:'p3m2_q5', question:'What is an important test before deploying an assistant?', options:['Whether every screen contains AI.','Whether the full workflow works from input to output, including verification, human hand-offs and failure cases.','Whether the prompt is as long as possible.','Whether users can avoid seeing any sources.'], correctIndex:1, explanation:'End-to-end testing exposes failures in hand-offs, verification and fallback behaviour.' },
  ],
};
