import { Lesson } from './types';

export const levelFourCommunityProblemsLesson: Lesson = {
  id: 'MZAIE-P4-M01-L01',
  title: 'Solving Real Community Problems',
  levelId: 'MZAIE-P4',
  moduleId: 'MZAIE-P4-M01',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Frame a meaningful community problem before proposing technology.',
    'Identify who is affected, whose voices may be missing and what constraints shape the problem.',
    'Define a useful, realistic improvement that can be observed or measured.',
    'Choose the smallest responsible intervention and keep people accountable for important decisions.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p4m1_b1', type:'objective', variant:'standard', content:'Lead a responsible response to a real local challenge by understanding the people, evidence, constraints and desired improvement before deciding whether AI belongs in the solution.' },
    { id:'p4m1_b2', type:'explanation', variant:'standard', content:'A community problem is rarely just a technology problem. It may involve cost, language, transport, trust, disability access, limited data, outdated information, staff capacity or unequal access to services. Good problem-solving begins by seeing the whole situation.' },
    { id:'p4m1_b3', type:'keyPoint', variant:'standard', content:'Do not ask “Where can we use AI?” Ask “What is preventing people from getting a useful outcome, and what is the simplest responsible way to improve it?”' },
    { id:'p4m1_b4', type:'application', variant:'plain', content:'Use the COMMUNITY loop: Clarify the need. Observe the real setting. Map who is affected. Map barriers and existing resources. Understand whose voice is missing. Name the improvement you want. Identify the smallest useful intervention. Test with people. Yield to evidence and improve.' },
    { id:'p4m1_b5', type:'example', variant:'SouthAfricanContext', content:'A community organisation notices that residents repeatedly miss municipal service updates. The first question is not whether to build a chatbot. The team checks where residents currently get information, which languages are used, whether data costs are a barrier, which notices change frequently and which residents are being excluded.' },
    { id:'p4m1_b6', type:'explanation', variant:'standard', content:'Separate symptoms from the underlying problem. “People keep asking the same question” is a symptom. The deeper problem might be unclear wording, inaccessible websites, changing information, language barriers or a process that assumes everyone has reliable internet.' },
    { id:'p4m1_b7', type:'keyPoint', variant:'standard', content:'Local relevance is evidence, not decoration. A solution designed for South African communities must account for the actual devices, languages, connectivity, costs, institutions and human relationships in the setting where it will be used.' },
    { id:'p4m1_b8', type:'example', variant:'SouthAfricanContext', content:'A TVET college wants to reduce queues for routine student enquiries. Interviews show that many questions concern a small set of deadlines and document requirements. A lightweight phone-friendly information guide with verified content and offline access may solve more of the problem than an always-online AI assistant.' },
    { id:'p4m1_b9', type:'verification', variant:'standard', content:'Triangulate the problem before acting. Combine at least two forms of evidence where practical, such as user conversations, observation, service records, repeated enquiries, official documents or a small pilot. AI-generated assumptions are not community evidence.' },
    { id:'p4m1_b10', type:'ethicsCheck', variant:'standard', content:'Ask who benefits, who could be excluded, who carries the risk if the solution is wrong, what personal information is truly necessary, and who has authority to correct or stop the system. A useful result for the majority can still harm a smaller group.' },
    { id:'p4m1_b11', type:'application', variant:'SouthAfricanContext', content:'Suppose an NGO wants to help job seekers find opportunities. Start by identifying whether the main barrier is discovery, data cost, CV quality, language, eligibility confusion or lack of digital skills. The answer changes the solution. AI might help simplify verified information or improve drafts, but it should not invent vacancies, qualifications or application requirements.' },
    { id:'p4m1_b12', type:'activity', variant:'standard', content:'Choose one genuine local problem. Write: 1) the people affected, 2) the observable problem, 3) evidence that it exists, 4) three barriers or constraints, 5) one group whose voice could be missed, 6) the useful improvement you want, 7) the simplest non-AI response, 8) where AI could add value, 9) one risk, and 10) one small test you could run before scaling.' },
    { id:'p4m1_b13', type:'reflection', variant:'standard', content:'Would the people affected describe the problem in the same way you have? What would you change if their priorities were different from yours?' },
    { id:'p4m1_b14', type:'summary', variant:'standard', content:'Responsible community problem-solving starts with people and evidence. Understand the setting, distinguish symptoms from causes, include voices that may be missed, define a useful improvement, choose the simplest suitable intervention, protect people from avoidable harm and learn from a small real-world test before scaling.' },
  ],
  quiz: [
    { id:'p4m1_q1', question:'What is the strongest starting question for a community AI project?', options:['Which AI tool should we buy?','What prevents people from getting a useful outcome, and what would improve it?','How many AI features can we add?','Which technology is newest?'], correctIndex:1, explanation:'The problem and desired human outcome should be understood before technology is selected.' },
    { id:'p4m1_q2', question:'Why should you separate symptoms from underlying causes?', options:['To make the project sound more technical.','Because the visible complaint may be caused by a different barrier such as language, cost or inaccessible information.','Because symptoms never matter.','So that AI can make the final decision.'], correctIndex:1, explanation:'Treating only a symptom can leave the real barrier unchanged.' },
    { id:'p4m1_q3', question:'Which is the strongest evidence that a community problem exists?', options:['An AI-generated description of the problem.','A single assumption from the project team.','Evidence from users and the real workflow, supported where possible by records or observation.','A popular technology trend.'], correctIndex:2, explanation:'Real-world evidence from affected people and the setting is stronger than assumptions or generated claims.' },
    { id:'p4m1_q4', question:'What does human-centred local relevance require?', options:['Adding South African place names to a generic solution.','Designing around actual devices, languages, costs, connectivity and community circumstances.','Using AI for every part of the service.','Requiring users to upgrade their phones.'], correctIndex:1, explanation:'Local relevance comes from designing around real conditions and people, not cosmetic localisation.' },
    { id:'p4m1_q5', question:'What should happen before a community solution is scaled?', options:['Add as many features as possible.','Run a small responsible test, collect evidence and improve from what happens.','Remove human oversight.','Collect personal information from everyone.'], correctIndex:1, explanation:'A small test reveals whether the proposed intervention actually helps and exposes risks before wider deployment.' },
  ],
};
