import { Lesson } from './types';

export const levelThreeSouthAfricanPrototypeLesson: Lesson = {
  id: 'MZAIE-P3-M08-L01',
  title: 'Build a South African AI Prototype',
  levelId: 'MZAIE-P3',
  moduleId: 'MZAIE-P3-M08',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Combine the Level 3 skills into one small responsible AI prototype for a real South African need.',
    'Define the user, problem, minimum useful feature set and evidence of value before building.',
    'Apply source, data, UX, testing, bias, privacy and deployment gates to the prototype.',
    'Create a compact prototype evidence pack that shows what passed, what failed and what must improve next.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p3m8_b1', type:'objective', variant:'standard', content:'This capstone brings Level 3 together. Your goal is not to build the biggest AI product. Your goal is to build the smallest responsible prototype that solves one clear problem for one defined group of people.' },
    { id:'p3m8_b2', type:'keyPoint', variant:'standard', content:'Start with the problem, not the tool. Write one sentence: Who is struggling, with what task, in which setting, and what better outcome would matter?' },
    { id:'p3m8_b3', type:'example', variant:'SouthAfricanContext', content:'Example: A community skills centre wants to help first-time job seekers understand vacancies written in difficult English. A small prototype could explain one vacancy in plain language, identify required documents and generate a simple checklist. It does not need to become a full recruitment platform.' },
    { id:'p3m8_b4', type:'application', variant:'plain', content:'Use the BUILD-8 capstone sequence: 1) Problem and user. 2) Intended outcome. 3) Minimum inputs. 4) Trusted knowledge or sources. 5) Smallest useful workflow. 6) Simple user experience. 7) Test and safety gates. 8) Evidence and next decision.' },
    { id:'p3m8_b5', type:'explanation', variant:'standard', content:'Freeze the minimum viable prototype before building. Choose one primary user, one core task and one useful output. Remove anything that is not required to test the central value proposition.' },
    { id:'p3m8_b6', type:'keyPoint', variant:'standard', content:'Design for the real environment. Consider ordinary Android phones, limited data, intermittent connectivity, shared devices, plain language, local terminology, accessibility and whether the core experience can still make sense when an external AI or video service is unavailable.' },
    { id:'p3m8_b7', type:'explanation', variant:'standard', content:'Apply the knowledge and data rules from Module 3.3. Record what the prototype is allowed to use, which sources are trusted, how freshness is checked, what personal or sensitive information is excluded, and what the system must say when it is uncertain.' },
    { id:'p3m8_b8', type:'explanation', variant:'standard', content:'Apply the workflow and UX rules from Modules 3.2 and 3.5. Keep the user journey short. Each screen or conversation step should have a clear purpose, a clear next action, understandable feedback and a safe way to recover from an error.' },
    { id:'p3m8_b9', type:'ethicsCheck', variant:'standard', content:'Before testing, define what the AI may never decide alone. High-impact decisions about health, legal rights, employment, discipline, finance or personal safety require stronger human review and trusted-source verification.' },
    { id:'p3m8_b10', type:'application', variant:'standard', content:'Create at least eight test cases: two normal cases, two difficult or incomplete inputs, one weak-connectivity or service-failure case, one factual-verification case, one language or fairness case, and one harmful or unsafe request. Record PASS, FAIL or NEEDS WORK and the reason.' },
    { id:'p3m8_b11', type:'example', variant:'SouthAfricanContext', content:'A school support prototype should be tested with the kinds of language, spelling, device limitations and curriculum questions learners actually use. A prototype that works only with polished English on a fast laptop has not yet proved that it works for the intended user.' },
    { id:'p3m8_b12', type:'keyPoint', variant:'standard', content:'A failed test is useful evidence. Do not hide it. Record the failure, decide whether it is a BLOCKER or an improvement, and change the prototype only where the evidence justifies the change.' },
    { id:'p3m8_b13', type:'explanation', variant:'standard', content:'Run the privacy and deployment gate from Module 3.7 before any real pilot. Confirm minimum data, consent where needed, access boundaries, human oversight, stop-pilot conditions, revoke or rollback method and recovery plan.' },
    { id:'p3m8_b14', type:'activity', variant:'standard', content:'Build your Level 3 Prototype Evidence Pack. Include: prototype name, user, problem statement, intended outcome, one-sentence value proposition, core workflow, minimum data, trusted sources, screenshots or notes of the prototype, eight test results, known limitations, privacy/safety gate, what users liked or struggled with, and one next action. End with one decision: READY FOR SMALL PILOT, NEEDS REPAIR or STOP.' },
    { id:'p3m8_b15', type:'reflection', variant:'standard', content:'What evidence would convince you that your prototype is genuinely useful to the intended South African user, rather than merely impressive to the builder?' },
    { id:'p3m8_b16', type:'summary', variant:'standard', content:'Level 3 ends with evidence, not hype. Define one real need, build the smallest useful solution, design for the actual user environment, control sources and data, test normal and failure cases, check bias and safety, document limitations and make a disciplined pilot decision.' },
  ],
  quiz: [
    { id:'p3m8_q1', question:'What is the best starting point for the Level 3 capstone?', options:['Choose the most advanced AI tool.','Define one real user problem and desired outcome.','Collect as much data as possible.','Add every possible feature.'], correctIndex:1, explanation:'The capstone starts with a defined user problem and useful outcome, not with technology.' },
    { id:'p3m8_q2', question:'What should the smallest useful prototype contain?', options:['Only the features needed to test the core value proposition.','Every feature planned for the final product.','A complex backend whether needed or not.','Only a logo and landing page.'], correctIndex:0, explanation:'A controlled prototype keeps scope small so the central value can be tested quickly and honestly.' },
    { id:'p3m8_q3', question:'Why include weak-connectivity and language cases in testing?', options:['Because they reflect real conditions many intended users may face.','Only to make the test list longer.','Because every prototype must be translated into every language immediately.','To avoid testing factual accuracy.'], correctIndex:0, explanation:'Testing should reflect the actual user environment, including connectivity and language constraints.' },
    { id:'p3m8_q4', question:'What should happen when an important test fails?', options:['Hide the failure before showing anyone.','Record it, classify its seriousness and repair only where evidence justifies change.','Mark the whole prototype complete anyway.','Delete all test results.'], correctIndex:1, explanation:'A failed test is evidence that supports a disciplined repair or stop decision.' },
    { id:'p3m8_q5', question:'What is the strongest end point for the capstone?', options:['A claim that the prototype is perfect.','A documented evidence pack and a clear READY, NEEDS REPAIR or STOP decision.','A promise to add more features.','A social-media post before testing.'], correctIndex:1, explanation:'The capstone ends with documented evidence and a controlled decision about what happens next.' },
  ],
};
