import { Lesson } from './types';

export const levelFourLeadershipEthicsGovernanceLesson: Lesson = {
  id: 'MZAIE-P4-M07-L01',
  title: 'Leadership, Ethics & Governance',
  levelId: 'MZAIE-P4',
  moduleId: 'MZAIE-P4-M07',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Define governance rules for responsible AI use in teams, organisations and communities.',
    'Set clear accountability, human oversight, escalation and review points for AI-supported work.',
    'Identify ethical risks before deploying AI in real services or decisions.',
    'Create a simple AI use policy that protects people, evidence, privacy and dignity.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p4m7_b1', type:'objective', variant:'standard', content:'Lead AI use responsibly by setting rules for who may use AI, what it may be used for, what must be checked, and who remains accountable when something goes wrong.' },
    { id:'p4m7_b2', type:'explanation', variant:'standard', content:'AI governance is not paperwork for large companies only. A school, NGO, church, small business or community project also needs clear rules when AI affects people, information, services or trust.' },
    { id:'p4m7_b3', type:'keyPoint', variant:'standard', content:'Accountability cannot be outsourced to AI. A named person, team or institution must remain responsible for decisions, corrections and harm prevention.' },
    { id:'p4m7_b4', type:'application', variant:'plain', content:'Use the GOVERN loop: Goal. Oversight. Verification. Evidence. Risk limits. Names of responsible people. This turns good intentions into practical control.' },
    { id:'p4m7_b5', type:'example', variant:'SouthAfricanContext', content:'A TVET college uses AI to support student enquiries. Governance rules should say which answers may be automated, which must be checked by staff, how outdated information is corrected, and where students go if the tool gives confusing advice.' },
    { id:'p4m7_b6', type:'explanation', variant:'standard', content:'Ethical leadership asks practical questions: Is the source reliable? Is personal data protected? Can users challenge the answer? Could the tool exclude people? Are staff trained enough to supervise it?' },
    { id:'p4m7_b7', type:'keyPoint', variant:'standard', content:'Good governance creates permission and limits at the same time. It allows useful AI adoption while preventing careless, hidden or unfair use.' },
    { id:'p4m7_b8', type:'example', variant:'SouthAfricanContext', content:'A church admin team may use AI to draft announcements, summaries and study questions. It should not use AI to expose pastoral conversations, make sensitive judgements about members, or publish unchecked claims.' },
    { id:'p4m7_b9', type:'verification', variant:'standard', content:'Review AI outputs according to risk. Low-risk drafts may need quick editing. High-impact outputs involving rights, money, safety, children, employment or personal information need stronger human review and clear records.' },
    { id:'p4m7_b10', type:'ethicsCheck', variant:'standard', content:'Ask who has power, who is affected, who can object, who checks the evidence, who fixes errors, and who carries responsibility if the AI-supported process causes harm.' },
    { id:'p4m7_b11', type:'application', variant:'SouthAfricanContext', content:'A small organisation can begin with a one-page AI use rule: allowed uses, banned uses, private information rule, source-checking rule, human review rule, escalation contact and review date.' },
    { id:'p4m7_b12', type:'activity', variant:'standard', content:'Draft a simple AI governance note. Include: 1) purpose, 2) allowed uses, 3) prohibited uses, 4) data that must not be entered, 5) source-checking rule, 6) human review rule, 7) escalation person, and 8) review date.' },
    { id:'p4m7_b13', type:'reflection', variant:'standard', content:'If someone was harmed by your AI-supported process, would they know who to contact and how the error would be corrected?' },
    { id:'p4m7_b14', type:'summary', variant:'standard', content:'Responsible AI leadership sets clear rules before deployment. Governance protects people through accountability, source checking, privacy limits, human oversight, escalation and regular review.' },
  ],
  quiz: [
    { id:'p4m7_q1', question:'What is the main purpose of AI governance?', options:['To slow down every project.','To set clear rules, accountability, oversight and limits for AI use.','To let AI make final decisions alone.','To remove human responsibility.'], correctIndex:1, explanation:'Governance makes AI use controlled, accountable and safer.' },
    { id:'p4m7_q2', question:'Who remains accountable when an AI-supported process affects people?', options:['The AI system.','A named person, team or institution.','Nobody if the model is advanced.','Only the user who asked the question.'], correctIndex:1, explanation:'Responsibility must remain with accountable humans or institutions.' },
    { id:'p4m7_q3', question:'Which AI use should require stronger review?', options:['Drafting a low-risk announcement.','Choosing font wording.','Guidance involving rights, money, safety, children or personal information.','Creating a simple checklist title.'], correctIndex:2, explanation:'High-impact uses need stronger human oversight and records.' },
    { id:'p4m7_q4', question:'What should a simple AI use policy include?', options:['Allowed uses, banned uses, data limits, review rules and escalation contact.','Only the name of the AI tool.','A promise that AI is always correct.','No limits, so people can experiment freely.'], correctIndex:0, explanation:'Practical governance needs clear permissions, limits and responsibility.' },
    { id:'p4m7_q5', question:'What is a warning sign of weak AI governance?', options:['Users can report errors.','Sources are checked.','No one knows who fixes mistakes or owns the risk.','High-risk outputs require review.'], correctIndex:2, explanation:'Unclear ownership and correction routes create serious governance risk.' },
  ],
};
