import { Lesson } from './types';

export const levelFourCapstoneSouthAfricanSolutionLesson: Lesson = {
  id: 'MZAIE-P4-M08-L01',
  title: 'Capstone: Build & Present a South African AI Solution',
  levelId: 'MZAIE-P4',
  moduleId: 'MZAIE-P4-M08',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 25,
  objectives: [
    'Combine the programme into a clear proposal for a responsible South African AI-supported solution.',
    'Show the problem, users, evidence, workflow, risks, governance and impact measures in one plan.',
    'Present the solution honestly, including limits, offline access and human oversight.',
    'Decide whether the idea is ready to test, needs revision or should be stopped.',
  ],
  competencyIds: ['AI_UNDERSTANDING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p4m8_b1', type:'objective', variant:'standard', content:'Complete the learning pathway by building and presenting a small, responsible AI-supported solution proposal for a genuine South African need.' },
    { id:'p4m8_b2', type:'explanation', variant:'standard', content:'A capstone is not a fantasy pitch. It is a disciplined proposal that shows the problem, people affected, evidence, practical workflow, offline access, risks, human oversight, governance and how impact will be measured.' },
    { id:'p4m8_b3', type:'keyPoint', variant:'standard', content:'A strong AI solution is useful, limited, explainable, testable and accountable. It does not pretend to solve everything.' },
    { id:'p4m8_b4', type:'application', variant:'plain', content:'Use the SOLUTION canvas: Situation. Outcome. Learners or users. Useful workflow. Technology role. Information sources. Oversight. Needs and constraints.' },
    { id:'p4m8_b5', type:'example', variant:'SouthAfricanContext', content:'A community learning centre proposes an offline-first AI study guide for Grade 9 learners. The proposal explains the reading problem, shared-phone reality, plain-language lessons, teacher review, no private learner data, offline access and a small pilot with five learners.' },
    { id:'p4m8_b6', type:'explanation', variant:'standard', content:'Your solution should include a non-AI fallback. If the AI or internet fails, people should still receive useful guidance, a checklist, a lesson, a referral path or a human contact point.' },
    { id:'p4m8_b7', type:'keyPoint', variant:'standard', content:'Do not hide risks in the final presentation. A trustworthy builder names limits, failure cases, privacy risks and what will be checked before wider use.' },
    { id:'p4m8_b8', type:'example', variant:'SouthAfricanContext', content:'A small-business support assistant may help owners draft customer messages and weekly plans. The capstone should show which business data is safe to use, what must stay private, who checks outputs and how customer trust will be protected.' },
    { id:'p4m8_b9', type:'verification', variant:'standard', content:'Before presenting, check the proposal against five tests: real need, real users, verified sources, clear human oversight and measurable improvement.' },
    { id:'p4m8_b10', type:'ethicsCheck', variant:'standard', content:'Ask whether the proposed solution respects dignity, reduces exclusion, protects private information, keeps humans accountable and can be challenged or corrected if it fails.' },
    { id:'p4m8_b11', type:'application', variant:'SouthAfricanContext', content:'Your first pilot should be small: one setting, one user group, one workflow, one responsible person, one feedback route and one clear decision about what success or failure means.' },
    { id:'p4m8_b12', type:'activity', variant:'standard', content:'Create your capstone proposal with these headings: 1) problem, 2) people affected, 3) evidence, 4) proposed workflow, 5) AI role, 6) non-AI/offline fallback, 7) privacy and safety limits, 8) human oversight, 9) impact measures, 10) pilot plan, and 11) decision: test, revise or stop.' },
    { id:'p4m8_b13', type:'reflection', variant:'standard', content:'Would you be willing to test this solution with real people and accept their evidence even if it proves your first idea is wrong?' },
    { id:'p4m8_b14', type:'summary', variant:'standard', content:'The capstone brings the programme together. A responsible South African AI solution begins with a real need, serves real users, works within local constraints, protects dignity and privacy, keeps human oversight, measures impact and starts with a small honest pilot.' },
  ],
  quiz: [
    { id:'p4m8_q1', question:'What should a capstone AI solution proposal prove?', options:['That the idea sounds impressive.','That it addresses a real need with evidence, oversight, limits and measurable improvement.','That AI can replace everyone involved.','That no testing is needed.'], correctIndex:1, explanation:'A capstone must show usefulness, responsibility and testability.' },
    { id:'p4m8_q2', question:'Why include a non-AI or offline fallback?', options:['Because the solution should still help when internet, AI or data access fails.','Because AI is never useful.','Because fallback pages look professional.','Because users should avoid technology completely.'], correctIndex:0, explanation:'Offline and fallback support protect access in real conditions.' },
    { id:'p4m8_q3', question:'Which is a strong pilot design?', options:['Launch everywhere immediately.','One setting, one user group, one workflow, clear feedback and a responsible person.','No feedback so the project moves faster.','Use only AI-generated evidence.'], correctIndex:1, explanation:'A narrow pilot gives safer evidence before scaling.' },
    { id:'p4m8_q4', question:'What should be named honestly in the presentation?', options:['Only the benefits.','Benefits, limits, risks, human oversight and impact measures.','Only the technology used.','Only the final design colours.'], correctIndex:1, explanation:'Responsible presentation includes both promise and limits.' },
    { id:'p4m8_q5', question:'What is the correct decision if evidence shows the solution is not helping?', options:['Ignore the evidence.','Revise, pause or stop rather than scaling harm.','Add more features immediately.','Hide the test results.'], correctIndex:1, explanation:'Evidence should guide whether to improve, pause or stop.' },
  ],
};
