import { Lesson } from './types';

export const levelTwoWorkProductivityLesson: Lesson = {
  id: 'MZAIE-P2-M06-L01',
  title: 'AI for Work & Productivity',
  levelId: 'MZAIE-P2',
  moduleId: 'MZAIE-P2-M06',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Use AI to break work into clear tasks, priorities and next actions.',
    'Use AI to support planning, meeting notes, checklists and routine administration without losing human control.',
    'Verify workplace outputs before acting on them and protect confidential information.',
    'Use a repeatable productivity workflow that improves speed without replacing judgement or accountability.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p2m6_b1', type:'objective', variant:'standard', content:'Learn to use AI as a productivity assistant for planning, organising and reviewing work while keeping decisions, responsibility and confidential information under human control.' },
    { id:'p2m6_b2', type:'explanation', variant:'standard', content:'AI is useful when work is messy or repetitive. It can turn rough notes into a task list, suggest an order of work, create a checklist, summarise a non-sensitive meeting note, draft a follow-up list or help organise a simple workflow.' },
    { id:'p2m6_b3', type:'keyPoint', variant:'standard', content:'Productivity is not the same as speed. A fast AI-generated plan that misses a deadline, invents a task or exposes private information can create more work than it saves.' },
    { id:'p2m6_b4', type:'application', variant:'plain', content:'Use the PLAN loop: Purpose: define the result you need. List: capture the real tasks and facts. Arrange: ask AI to group, sequence or prioritise them. Notice: check deadlines, dependencies, risks and missing information. Act: choose the next action yourself and review the result.' },
    { id:'p2m6_b5', type:'example', variant:'SouthAfricanContext', content:'A TVET student doing workplace exposure could give AI a non-sensitive list of weekly tasks and ask it to organise them into “urgent”, “this week” and “can wait”. The student should then check the priorities against the supervisor’s real deadlines before acting.' },
    { id:'p2m6_b6', type:'explanation', variant:'standard', content:'Meeting support works best when the human provides accurate notes. AI can help convert those notes into decisions, actions, owners and due dates, but it should not invent what people agreed to. The final action list must be checked against the actual meeting.' },
    { id:'p2m6_b7', type:'example', variant:'SouthAfricanContext', content:'A small community organisation preparing for a Saturday event could ask AI to turn a rough list into a checklist for venue, transport, volunteers, materials and communication. The organiser must still confirm real people, costs, dates and responsibilities.' },
    { id:'p2m6_b8', type:'verification', variant:'standard', content:'Before using an AI-generated work plan, check names, dates, deadlines, amounts, responsibilities, policies, contact details and any assumption that could affect another person. If the information matters operationally, verify it from the original source.' },
    { id:'p2m6_b9', type:'ethicsCheck', variant:'standard', content:'Do not paste confidential client information, passwords, ID numbers, private HR records, disciplinary matters, medical information, unpublished financial data or restricted workplace documents into an AI service unless you are authorised and the service is appropriate for that data.' },
    { id:'p2m6_b10', type:'application', variant:'SouthAfricanContext', content:'AI can help when data is limited or connectivity is unreliable by preparing a simple offline checklist, short message template or step-by-step plan that can be saved on the phone and used later without needing the AI again.' },
    { id:'p2m6_b11', type:'activity', variant:'standard', content:'Choose one real, non-sensitive task you need to complete this week. Write the goal and all known tasks first. Ask AI to group and prioritise them. Then mark one suggestion you accept, one you change and one thing the AI missed. Write your final next action yourself.' },
    { id:'p2m6_b12', type:'reflection', variant:'standard', content:'Think about a task where AI could save you time. Which part should AI handle, and which part still needs your judgement because the consequences matter?' },
    { id:'p2m6_b13', type:'keyPoint', variant:'standard', content:'A good AI productivity tool should leave you with a clearer plan, not less understanding. You should still know what must happen, why it matters, who is responsible and what needs checking.' },
    { id:'p2m6_b14', type:'summary', variant:'standard', content:'Use AI to organise, prioritise, summarise and prepare routine work. Start with real facts, protect private information, verify important details and keep human responsibility for priorities and decisions.' },
  ],
  quiz: [
    { id:'p2m6_q1', question:'What is the best use of AI for workplace productivity?', options:['Let AI make every decision without review.','Use AI to organise tasks, then check priorities and facts yourself.','Paste all confidential records so the plan is detailed.','Accept the first task list even if deadlines are wrong.'], correctIndex:1, explanation:'AI can help organise work, but the human must verify priorities, facts and consequences.' },
    { id:'p2m6_q2', question:'In the PLAN loop, what happens before you act?', options:['You check deadlines, dependencies, risks and missing information.','You delete the original notes.','You assume the AI has already verified everything.','You send the plan to everyone immediately.'], correctIndex:0, explanation:'The Notice step is the review gate before action.' },
    { id:'p2m6_q3', question:'Why should AI-generated meeting actions be checked?', options:['AI may invent or misread what people actually agreed to.','Meeting notes are always private by law.','AI cannot organise actions.','Because every action must be written by hand.'], correctIndex:0, explanation:'AI can structure notes, but it can misinterpret or invent details, so the real agreement must be confirmed.' },
    { id:'p2m6_q4', question:'Which information should generally not be pasted into an AI tool for ordinary work planning?', options:['A public event date.','A non-sensitive checklist.','Private HR records and ID numbers.','A generic task title.'], correctIndex:2, explanation:'Sensitive or confidential workplace information should be protected.' },
    { id:'p2m6_q5', question:'What is the strongest sign that AI improved productivity responsibly?', options:['The response was very long.','You understand the final plan, verified the important details and know the next action.','The AI used complicated language.','You did not need to read the output.'], correctIndex:1, explanation:'Responsible productivity improves clarity and action while keeping human understanding and accountability.' },
  ],
};
