import { Lesson } from './types';

export const levelThreeConversationUxLesson: Lesson = {
  id: 'MZAIE-P3-M05-L01',
  title: 'Conversation & User Experience Design',
  levelId: 'MZAIE-P3',
  moduleId: 'MZAIE-P3-M05',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Design simple conversations and screens that help users know what to do next.',
    'Use plain language, clear prompts, feedback and error messages for ordinary mobile users.',
    'Plan accessibility, multilingual support, weak-connectivity behaviour and human handoff.',
    'Test whether the experience works for real people, not only for the builder.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'UBUNTU_TECHNOLOGY_AWARENESS', 'CRITICAL_QUESTIONING'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p3m5_b1', type:'objective', variant:'standard', content:'Design an AI experience that feels clear, respectful and usable on an ordinary phone, including what the user sees, what they type, what happens when something goes wrong, and when a human must take over.' },
    { id:'p3m5_b2', type:'explanation', variant:'standard', content:'User experience is not decoration. It is the complete path a person follows through the solution: understanding the purpose, entering information, receiving a result, correcting mistakes, knowing what to trust and knowing what to do next.' },
    { id:'p3m5_b3', type:'keyPoint', variant:'standard', content:'A powerful AI model can still create a poor product if users cannot understand the instructions, buttons, questions or limitations. Clarity is part of functionality.' },
    { id:'p3m5_b4', type:'application', variant:'plain', content:'Use the CLEAR flow: Clarify the purpose. Lead with one obvious next action. Explain what information is needed. Acknowledge the user input and show progress or feedback. Recover from errors with a useful next step.' },
    { id:'p3m5_b5', type:'example', variant:'SouthAfricanContext', content:'A bursary-help assistant should not begin with “How may I assist?” and leave the learner guessing. It could begin with three plain choices: “Check eligibility”, “See required documents”, or “Find the closing date”. This reduces typing, data use and confusion on a small screen.' },
    { id:'p3m5_b6', type:'explanation', variant:'standard', content:'Write interface language for the user, not for the developer. Prefer short familiar words, one instruction at a time, descriptive buttons and visible examples. Avoid technical labels such as “execute workflow”, “submit payload” or “invoke model” when “Continue”, “Send” or “Check answer” would be clearer.' },
    { id:'p3m5_b7', type:'keyPoint', variant:'standard', content:'Good error messages explain what happened and what the user can do next. “Something went wrong” is weak. “The connection dropped. Your draft is still saved. Try again when you have data.” is useful.' },
    { id:'p3m5_b8', type:'application', variant:'SouthAfricanContext', content:'Design for ordinary Android phones and uneven connectivity. Keep screens light, avoid forced video, minimise large downloads, preserve typed work where possible and make important instructions available offline.' },
    { id:'p3m5_b9', type:'explanation', variant:'standard', content:'Accessibility means more than font size. Consider readable contrast, large tap targets, simple navigation, screen-reader-friendly labels, plain language, limited cognitive load and alternatives to audio-only or image-only information.' },
    { id:'p3m5_b10', type:'example', variant:'SouthAfricanContext', content:'A community learning tool might offer English plus Afrikaans or isiXhosa support, while keeping important technical terms consistent with the official learning material. Translation should be tested with real speakers instead of assuming machine translation is always correct.' },
    { id:'p3m5_b11', type:'ethicsCheck', variant:'standard', content:'Do not design the interface to pressure people into sharing unnecessary personal information or accepting an AI answer. Make uncertainty visible, explain important limitations, and provide a clear human-contact or escalation path for high-impact situations.' },
    { id:'p3m5_b12', type:'verification', variant:'standard', content:'Test the full experience with realistic tasks. Watch where people hesitate, tap the wrong control, misunderstand a message, abandon the task or assume the AI is more certain than it is. Fix those points before adding more features.' },
    { id:'p3m5_b13', type:'activity', variant:'standard', content:'Choose the prototype from your earlier Level 3 work. Sketch four mobile screens or conversation steps: 1) welcome/purpose, 2) user input, 3) AI-assisted result, 4) error or human-handoff state. For each, write the exact words the user sees and the one next action you want them to take.' },
    { id:'p3m5_b14', type:'reflection', variant:'standard', content:'Could a first-time user understand your solution without you standing next to them? If not, what part of the design is depending on your private knowledge as the builder?' },
    { id:'p3m5_b15', type:'summary', variant:'standard', content:'A good AI experience is clear, mobile-friendly, accessible, honest about uncertainty and easy to recover from when something fails. Design the conversation and screens around real people, real devices and real constraints, then test with users before adding complexity.' },
  ],
  quiz: [
    { id:'p3m5_q1', question:'What is the strongest sign of good user experience design?', options:['The interface uses many advanced controls.','A first-time user can understand the purpose and next action without extra explanation.','The screen contains as much information as possible.','The builder personally likes the design.'], correctIndex:1, explanation:'Good UX reduces confusion and helps a real user complete the task independently.' },
    { id:'p3m5_q2', question:'Which error message is most useful?', options:['Error 502.','Something went wrong.','The connection dropped. Your draft is saved. Try again when you have data.','Invalid state exception.'], correctIndex:2, explanation:'A useful error message explains the problem in plain language and gives the user a next step.' },
    { id:'p3m5_q3', question:'Why can multiple-choice starting options be useful on a mobile AI assistant?', options:['They always make AI more accurate.','They reduce typing, data use and uncertainty about what the user can do.','They remove the need for accessibility testing.','They guarantee every user has the same problem.'], correctIndex:1, explanation:'Clear choices can reduce cognitive load and make a small-screen interaction easier.' },
    { id:'p3m5_q4', question:'What is the safest approach to multilingual AI interfaces?', options:['Assume automatic translation is always correct.','Use only English regardless of the users.','Test important translated content with real speakers and preserve official terminology where needed.','Translate every technical term differently to sound local.'], correctIndex:2, explanation:'Language support should be locally tested and should preserve important subject or official terminology.' },
    { id:'p3m5_q5', question:'When should an AI interface provide a human handoff?', options:['Only when the screen colour looks wrong.','When the issue is high-impact, sensitive, uncertain or outside the system’s safe scope.','Never, because AI should complete every task.','Only after the user has refreshed the page ten times.'], correctIndex:1, explanation:'Human escalation is important when consequences are significant or the AI should not make the final decision.' },
  ],
};
