import { Lesson } from './types';

export const levelTwoLessons: Lesson[] = [
  {
    id: 'MZAIE-P2-M01-L01',
    title: 'AI for Learning & Study',
    levelId: 'MZAIE-P2',
    moduleId: 'MZAIE-P2-M01',
    locale: 'en-ZA',
    version: '1.0',
    estimatedMinutes: 20,
    objectives: [
      'Use AI to explain, practise and review learning without replacing your own thinking.',
      'Turn notes or a topic into useful study questions, examples and revision plans.',
      'Check AI explanations against trusted learning material before relying on them.',
      'Use a repeatable study workflow that keeps the learner active and responsible.',
    ],
    competencyIds: ['AI_UNDERSTANDING', 'CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT'],
    activityIds: [],
    assessmentId: null,
    sourceIds: [],
    offlineEligible: true,
    trustState: 'AI_ASSISTED_REVIEWED',
    blocks: [
      {
        id: 'p2m1_b1',
        type: 'objective',
        variant: 'standard',
        content: 'Learn to use AI as a study partner that helps you understand, practise and improve, while you remain responsible for the learning and the final answer.',
      },
      {
        id: 'p2m1_b2',
        type: 'explanation',
        variant: 'standard',
        content: 'AI can support learning in several useful ways: it can explain a difficult idea in simpler language, generate practice questions, compare two concepts, give feedback on a draft answer, suggest a revision plan, or create another example when the first one does not make sense.',
      },
      {
        id: 'p2m1_b3',
        type: 'keyPoint',
        variant: 'standard',
        content: 'The goal is not to get AI to do the schoolwork for you. The goal is to use AI to make your own thinking stronger. If the AI does all the remembering, reasoning and writing, your output may improve while your learning does not.',
      },
      {
        id: 'p2m1_b4',
        type: 'application',
        variant: 'plain',
        content: 'Use the STUDY loop: Specify what you need to learn. Try it yourself first. Use AI for explanation, practice or feedback. Diagnose what you still do not understand. You do it again without copying the AI answer.',
      },
      {
        id: 'p2m1_b5',
        type: 'example',
        variant: 'SouthAfricanContext',
        content: 'A Grade 10 learner revising photosynthesis could first write what they remember, then ask: “Context: I am a Grade 10 learner in South Africa. Request: Explain photosynthesis in plain language. Examples: Use a vegetable garden. Output: Give five key points and three practice questions.” The learner should then answer the questions without looking at the explanation.',
      },
      {
        id: 'p2m1_b6',
        type: 'explanation',
        variant: 'standard',
        content: 'Retrieval practice is stronger than simply rereading. Instead of asking AI to summarise everything repeatedly, ask it to quiz you, hide the answers, wait for your response, then explain what you missed. This keeps your memory and reasoning active.',
      },
      {
        id: 'p2m1_b7',
        type: 'example',
        variant: 'SouthAfricanContext',
        content: 'A TVET learner preparing for an electrical trade theory assessment could ask AI to generate five short questions from their own non-sensitive notes, answer them on paper, then use the AI only to compare the answers and identify weak areas. The learner should still verify technical rules against the official learning material used by the college.',
      },
      {
        id: 'p2m1_b8',
        type: 'verification',
        variant: 'standard',
        content: 'AI can give a confident explanation that is incomplete, outdated or wrong. Check important definitions, formulas, dates, rules and prescribed content against your textbook, teacher or lecturer material, official curriculum sources, or another trusted source.',
      },
      {
        id: 'p2m1_b9',
        type: 'ethicsCheck',
        variant: 'standard',
        content: 'Do not upload passwords, ID numbers, private learner records, confidential school documents or another person’s personal information just to get study help. Use only the information needed for the task.',
      },
      {
        id: 'p2m1_b10',
        type: 'application',
        variant: 'SouthAfricanContext',
        content: 'AI can also support multilingual learning. You may ask for a difficult English concept to be explained more simply or compared with familiar local examples. But important subject terminology should still match the language and wording required by your school, college or assessment.',
      },
      {
        id: 'p2m1_b11',
        type: 'activity',
        variant: 'standard',
        content: 'Choose one topic you are currently learning. First write three things you already know. Then use AI to create five practice questions. Answer them without help. Finally, ask AI to explain only the questions you got wrong and write one corrected explanation in your own words.',
      },
      {
        id: 'p2m1_b12',
        type: 'reflection',
        variant: 'standard',
        content: 'Think about your last study session. Did technology help you think, practise and remember, or did it mostly give you finished answers? What would you change next time?',
      },
      {
        id: 'p2m1_b13',
        type: 'keyPoint',
        variant: 'standard',
        content: 'A useful study assistant should make you more capable without it. If you can explain the idea, answer a fresh question and apply it in a new situation after closing the AI tool, the learning has probably transferred to you.',
      },
      {
        id: 'p2m1_b14',
        type: 'summary',
        variant: 'standard',
        content: 'Use AI to explain, quiz, compare and give feedback, not to replace your own learning. Try first, ask clearly, verify important claims, practise again, and keep human judgement in control.',
      },
    ],
    quiz: [
      {
        id: 'p2m1_q1',
        question: 'Which use of AI is most likely to strengthen learning?',
        options: [
          'Ask AI to complete every homework question and copy the answers.',
          'Ask AI to quiz you, answer without help, then review the mistakes.',
          'Ask AI to shorten every textbook chapter so you never read the source.',
          'Ask AI to write an assignment and submit it unchanged.',
        ],
        correctIndex: 1,
        explanation: 'Answering from memory and then reviewing mistakes keeps the learner active and uses AI as feedback rather than a substitute for thinking.',
      },
      {
        id: 'p2m1_q2',
        question: 'What does the “Try it yourself first” step in the STUDY loop achieve?',
        options: [
          'It shows what you already understand and where you need help.',
          'It guarantees the AI answer will be correct.',
          'It removes the need for any verification.',
          'It makes the AI use less electricity.',
        ],
        correctIndex: 0,
        explanation: 'Trying first reveals your current understanding so AI support can target real gaps instead of doing the whole task for you.',
      },
      {
        id: 'p2m1_q3',
        question: 'A learner receives an AI explanation of an important formula. What should they do next?',
        options: [
          'Assume it is correct because the answer sounds confident.',
          'Post it immediately to the class group.',
          'Check it against trusted learning material before relying on it.',
          'Delete the textbook because the AI is faster.',
        ],
        correctIndex: 2,
        explanation: 'Important factual and technical content should be checked against trusted course or official learning material.',
      },
      {
        id: 'p2m1_q4',
        question: 'Which information should generally NOT be pasted into an AI tool for ordinary study help?',
        options: [
          'A public topic such as the water cycle.',
          'A short paragraph from your own non-sensitive notes.',
          'Your password, ID number or another learner’s private record.',
          'A question you wrote yourself.',
        ],
        correctIndex: 2,
        explanation: 'Sensitive personal or confidential information is unnecessary for ordinary study assistance and should be protected.',
      },
      {
        id: 'p2m1_q5',
        question: 'What is the best sign that AI-assisted studying has actually helped you learn?',
        options: [
          'The AI produced a long answer.',
          'You can explain and apply the idea yourself after closing the AI tool.',
          'You used the most advanced model available.',
          'You copied the answer without spelling mistakes.',
        ],
        correctIndex: 1,
        explanation: 'Real learning shows when you can recall, explain and apply the knowledge independently.',
      },
    ],
  },
];
