import { Lesson } from './types';

export const levelFourHumanCentredDesignLesson: Lesson = {
  id: 'MZAIE-P4-M02-L01',
  title: 'Human-Centred AI Design',
  levelId: 'MZAIE-P4',
  moduleId: 'MZAIE-P4-M02',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Design AI-supported solutions around people, dignity, access and real-world constraints.',
    'Identify user needs, barriers, risks and support requirements before choosing technology.',
    'Protect human judgement by defining clear handover, review and escalation points.',
    'Test whether a design is understandable, usable and fair for the people it is meant to serve.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p4m2_b1', type:'objective', variant:'standard', content:'Lead the design of an AI-supported service by starting with the people who must use it, the setting where it will operate, and the dignity, safety and access needs that must be protected.' },
    { id:'p4m2_b2', type:'explanation', variant:'standard', content:'Human-centred AI design means the technology is shaped around people, not the other way around. A good design considers language, literacy, disability access, device quality, data cost, trust, cultural context, staff capacity and what happens when the system is wrong.' },
    { id:'p4m2_b3', type:'keyPoint', variant:'standard', content:'A solution is not human-centred because it has a friendly interface. It is human-centred when real people can understand it, use it, question it, recover from errors and still receive fair treatment.' },
    { id:'p4m2_b4', type:'application', variant:'plain', content:'Use the PEOPLE design loop: People affected. Existing journey. Obstacles and risks. Plain-language need. Low-data access. Evidence to test. Oversight and escalation. This keeps design grounded before features are added.' },
    { id:'p4m2_b5', type:'example', variant:'SouthAfricanContext', content:'A school wants an AI homework helper. A human-centred design checks whether learners share phones, whether instructions are in plain language, whether the tool supports the curriculum, whether it explains instead of doing the work, and whether a teacher or adult can intervene when advice is confusing.' },
    { id:'p4m2_b6', type:'explanation', variant:'standard', content:'Design for the least powerful user in the situation. If the app only works for confident, connected users, it may widen the gap. Offline access, clear steps, forgiving screens and simple recovery are not extras. They are part of fairness.' },
    { id:'p4m2_b7', type:'keyPoint', variant:'standard', content:'Never replace accountability with automation. If an AI-supported service affects learning, money, health, rights, safety, employment or access to services, a responsible person or institution must remain answerable.' },
    { id:'p4m2_b8', type:'example', variant:'SouthAfricanContext', content:'An NGO uses AI to help residents understand documents. The design should avoid collecting unnecessary IDs or private details. It should explain that AI can make mistakes, give plain next steps, preserve offline guidance and refer serious legal, medical or safety issues to qualified people.' },
    { id:'p4m2_b9', type:'verification', variant:'standard', content:'Test the design with the people closest to the need. Ask them to complete a real task without coaching. Watch where they hesitate, misunderstand, abandon the task or need human help. Those moments are evidence, not user failure.' },
    { id:'p4m2_b10', type:'ethicsCheck', variant:'standard', content:'Ask whether the design respects dignity. Does it shame users? Does it assume high literacy? Does it require expensive data? Does it hide important decisions? Does it make it easy to challenge, correct or stop harmful output?' },
    { id:'p4m2_b11', type:'application', variant:'SouthAfricanContext', content:'For a small business assistant, a human-centred workflow may include a simple intake question, an AI draft, a human review step, a privacy warning, and a final checklist before sending anything to a customer. The AI supports judgement. It does not become the owner of the decision.' },
    { id:'p4m2_b12', type:'activity', variant:'standard', content:'Choose one AI-supported service idea. Write: 1) who will use it, 2) where they will use it, 3) one device or data constraint, 4) one language or literacy need, 5) one privacy risk, 6) one point where human review is required, 7) one error recovery step, and 8) one test with real users before wider use.' },
    { id:'p4m2_b13', type:'reflection', variant:'standard', content:'If the people most affected had the power to approve or reject your design, what would they ask you to change first?' },
    { id:'p4m2_b14', type:'summary', variant:'standard', content:'Human-centred AI design starts with people, context and consequences. Build around real access conditions, keep language plain, reduce data and privacy risks, protect human judgement, test with users and make sure errors can be questioned and corrected.' },
  ],
  quiz: [
    { id:'p4m2_q1', question:'What makes an AI design human-centred?', options:['It uses the newest AI model.','It is shaped around real people, access needs, risks and human oversight.','It removes all human decisions.','It collects as much information as possible.'], correctIndex:1, explanation:'Human-centred design starts with people, context, access and accountability.' },
    { id:'p4m2_q2', question:'Why should designers consider data cost, language and device quality?', options:['Because these conditions affect whether people can actually use the solution.','Because they make the app look more advanced.','Because AI cannot work on any phone.','Because users should always upgrade their devices.'], correctIndex:0, explanation:'Real-world constraints decide whether a design is accessible and fair.' },
    { id:'p4m2_q3', question:'When must human review be especially clear?', options:['When the system affects rights, safety, money, learning, employment or important services.','Only when the interface is colourful.','Only when the AI is slow.','Never, because AI output should be final.'], correctIndex:0, explanation:'High-impact decisions need accountable human oversight and escalation.' },
    { id:'p4m2_q4', question:'What is the strongest way to test a human-centred design?', options:['Ask only the project team if they like it.','Let real users try a real task and observe where they struggle or need help.','Assume the design works because it is simple.','Ask AI to declare the design complete.'], correctIndex:1, explanation:'Observed user behaviour gives stronger evidence than assumptions or internal opinions.' },
    { id:'p4m2_q5', question:'Which design choice best protects dignity?', options:['Use confusing warnings so users rely on the system.','Make errors easy to question, correct and escalate to a responsible person.','Hide uncertainty from users.','Collect private details before explaining why they are needed.'], correctIndex:1, explanation:'Dignity requires transparency, recovery, correction and accountable support.' },
  ],
};
