import { Lesson } from './types';

export const levelTwoAdvancedCreoLesson: Lesson = {
  id: 'MZAIE-P2-M03-L01',
  title: 'Advanced Prompting with CREO',
  levelId: 'MZAIE-P2',
  moduleId: 'MZAIE-P2-M03',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Extend CREO with constraints, examples, quality criteria and structured outputs.',
    'Break complex tasks into clear stages instead of asking for everything in one prompt.',
    'Diagnose weak AI responses and improve them with targeted follow-up prompts.',
    'Use prompting to improve usefulness while still protecting privacy and verifying important claims.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    {
      id: 'p2m3_b1',
      type: 'objective',
      variant: 'standard',
      content: 'Move beyond basic CREO by controlling the task more precisely, testing the result against clear criteria and improving only what is weak.',
    },
    {
      id: 'p2m3_b2',
      type: 'explanation',
      variant: 'standard',
      content: 'At Level 1 you learned CREO: Context, Request, Examples and Output. At Level 2 the same framework becomes more powerful when you add boundaries, quality criteria and a sequence for complex work. The goal is not to make prompts longer. The goal is to remove ambiguity.',
    },
    {
      id: 'p2m3_b3',
      type: 'keyPoint',
      variant: 'standard',
      content: 'Advanced prompting is controlled prompting. State what the AI should do, what it should not do, what information it may use, what quality standard matters and what the final result must look like.',
    },
    {
      id: 'p2m3_b4',
      type: 'application',
      variant: 'plain',
      content: 'Use CREO+: Context, Request, Examples, Output, plus Constraints and Check. Constraints define limits such as length, audience, source boundaries or excluded content. Check tells the AI what criteria the draft must satisfy before you accept it.',
    },
    {
      id: 'p2m3_b5',
      type: 'example',
      variant: 'SouthAfricanContext',
      content: 'A TVET student preparing a workplace email could prompt: “Context: I am applying for electrical workplace exposure. Request: Improve my draft. Examples: Respectful, direct South African workplace English. Output: Subject line plus email under 160 words. Constraints: Do not invent qualifications, dates or experience. Check: Confirm the final draft contains only facts I supplied.”',
    },
    {
      id: 'p2m3_b6',
      type: 'explanation',
      variant: 'standard',
      content: 'Complex tasks work better when divided into stages. Instead of asking for research, analysis, writing and final formatting in one instruction, first define the problem, then gather or provide trusted information, then create a draft, then review the draft against explicit criteria. Each stage gives you a point where human judgement can intervene.',
    },
    {
      id: 'p2m3_b7',
      type: 'example',
      variant: 'SouthAfricanContext',
      content: 'A small community organisation planning a youth workshop could use three prompts: first ask AI to organise the goals and audience, second ask it to turn approved facts into an agenda, and third ask it to check the agenda for clarity, timing and plain language. The organisation still verifies dates, venue details, costs and participant information itself.',
    },
    {
      id: 'p2m3_b8',
      type: 'keyPoint',
      variant: 'standard',
      content: 'Examples are strongest when they show the pattern you want. One useful example can guide tone or structure. A counterexample can also help: “Do not sound like a legal notice” or “Do not use academic jargon.” Use examples to clarify expectations, not to force the AI to copy wording.',
    },
    {
      id: 'p2m3_b9',
      type: 'application',
      variant: 'standard',
      content: 'When the first answer is weak, debug the prompt before starting over. Ask: Was the context too vague? Was the request too broad? Was the example misleading? Was the output format unclear? Were important constraints missing? Then change only the weak part and test again.',
    },
    {
      id: 'p2m3_b10',
      type: 'verification',
      variant: 'standard',
      content: 'A stronger prompt can improve relevance and consistency, but it cannot guarantee truth. For important claims, ask the AI to separate facts that need checking from suggestions or opinions, then verify the factual claims against trusted sources. Never treat prompt quality as a substitute for evidence.',
    },
    {
      id: 'p2m3_b11',
      type: 'ethicsCheck',
      variant: 'standard',
      content: 'Do not improve a prompt by adding unnecessary private information. Replace real names, ID numbers, learner records, confidential employer information or sensitive case details with neutral placeholders whenever the task can be completed without them.',
    },
    {
      id: 'p2m3_b12',
      type: 'activity',
      variant: 'standard',
      content: 'Take one prompt you used recently. Rewrite it as CREO+. Add one useful constraint and one quality check. Run both versions if you have access to an AI tool, compare the results, and identify exactly which change improved the answer. If offline, predict the difference and explain why.',
    },
    {
      id: 'p2m3_b13',
      type: 'reflection',
      variant: 'standard',
      content: 'When does adding more prompt detail improve the result, and when does it simply create clutter? How would you recognise the difference?',
    },
    {
      id: 'p2m3_b14',
      type: 'summary',
      variant: 'standard',
      content: 'Advanced prompting builds on CREO with constraints, quality checks, staged tasks and deliberate refinement. Keep prompts relevant rather than long, protect private information, diagnose weak outputs precisely and verify important claims independently.',
    },
  ],
  quiz: [
    {
      id: 'p2m3_q1',
      question: 'What is the main purpose of adding constraints to a CREO prompt?',
      options: [
        'To make every prompt as long as possible.',
        'To define useful limits and prevent unwanted output.',
        'To guarantee the AI is factually correct.',
        'To reveal more personal information.',
      ],
      correctIndex: 1,
      explanation: 'Constraints clarify boundaries such as length, audience, allowed information, exclusions and required standards.',
    },
    {
      id: 'p2m3_q2',
      question: 'What is usually the better approach for a complex task?',
      options: [
        'Ask for research, analysis and final publication in one vague sentence.',
        'Break the task into stages with a human review point between important steps.',
        'Remove all context so the AI can guess freely.',
        'Use only one-word prompts.',
      ],
      correctIndex: 1,
      explanation: 'Staged prompting makes complex work easier to inspect, correct and control before moving to the next step.',
    },
    {
      id: 'p2m3_q3',
      question: 'A response is too general. What is the best prompt-debugging move?',
      options: [
        'Add unrelated personal details.',
        'Identify which part of CREO is unclear and strengthen that part.',
        'Assume the AI cannot improve.',
        'Copy the answer anyway.',
      ],
      correctIndex: 1,
      explanation: 'Prompt debugging means locating the missing or weak instruction and correcting it deliberately rather than changing everything at once.',
    },
    {
      id: 'p2m3_q4',
      question: 'What does the “Check” in CREO+ do?',
      options: [
        'It tells the AI what criteria the draft should satisfy before you accept it.',
        'It guarantees every fact is true.',
        'It replaces human review.',
        'It asks for the user’s password.',
      ],
      correctIndex: 0,
      explanation: 'A quality check makes the expected standard explicit, but the human still reviews and verifies important information.',
    },
    {
      id: 'p2m3_q5',
      question: 'Does advanced prompting remove the need to verify important factual claims?',
      options: [
        'Yes, if the prompt uses CREO+.',
        'No. Better prompts improve direction, but evidence still needs checking.',
        'Yes, if the answer is well written.',
        'Only when the prompt contains examples.',
      ],
      correctIndex: 1,
      explanation: 'Prompt quality and factual verification are separate responsibilities. Important claims still require trusted evidence.',
    },
  ],
};
