import { Lesson } from './types';

export const levelThreeProblemSolutionLesson: Lesson = {
  id: 'MZAIE-P3-M01-L01',
  title: 'From Problem to AI Solution',
  levelId: 'MZAIE-P3',
  moduleId: 'MZAIE-P3-M01',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Define a real problem clearly before choosing an AI tool.',
    'Identify the people affected, their context and what a useful outcome would look like.',
    'Decide whether AI is appropriate, unnecessary or potentially harmful for the task.',
    'Sketch the smallest responsible solution that can be tested with real users.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p3m1_b1', type:'objective', variant:'standard', content:'Move from using AI tools to thinking like a responsible builder: define the problem, understand the people affected, decide whether AI is useful, and design the smallest solution worth testing.' },
    { id:'p3m1_b2', type:'explanation', variant:'standard', content:'Builders often fail when they begin with a tool instead of a need. “We should build a chatbot” is not a problem statement. “First-year TVET learners cannot easily find current bursary deadlines on a phone” is a problem that can be investigated.' },
    { id:'p3m1_b3', type:'keyPoint', variant:'standard', content:'Problem first, technology second. A good AI solution starts with a clear human need, a defined user and a measurable improvement.' },
    { id:'p3m1_b4', type:'application', variant:'plain', content:'Use the SOLUTION loop: State the problem. Observe the people and context. List the current obstacles. Understand what success means. Test whether AI adds real value. Identify risks and human responsibilities. Outline the smallest useful prototype. Next, test it with real users.' },
    { id:'p3m1_b5', type:'example', variant:'SouthAfricanContext', content:'A community advice office receives repeated questions about public-service application requirements. Before building anything, the team records the most common questions, checks which answers change over time, notes that many users rely on older Android phones, and decides that a lightweight verified FAQ may solve most of the problem without needing a complex AI chatbot.' },
    { id:'p3m1_b6', type:'explanation', variant:'standard', content:'Ask five questions before using AI: Who has the problem? What are they trying to achieve? What prevents them from doing it now? Which part is repetitive, language-heavy, information-heavy or difficult to navigate? What must remain a human decision?' },
    { id:'p3m1_b7', type:'keyPoint', variant:'standard', content:'Not every problem needs AI. If a static checklist, better signposting, a downloadable form, a spreadsheet or clearer instructions solve the problem reliably, use the simpler option.' },
    { id:'p3m1_b8', type:'example', variant:'SouthAfricanContext', content:'A small church wants volunteers to know who is on duty each Sunday. Generative AI is unnecessary. A simple offline roster is cheaper, clearer and more reliable. AI might become useful later if the task changes to summarising many volunteer messages or producing multilingual notices.' },
    { id:'p3m1_b9', type:'verification', variant:'standard', content:'Before designing a solution around a claimed problem, verify the problem with evidence. Speak to users, inspect the current workflow, count repeated requests, review existing documents or observe where people get stuck. Do not build from assumptions alone.' },
    { id:'p3m1_b10', type:'ethicsCheck', variant:'standard', content:'A useful solution can still be unsafe. Ask whether it collects personal information, affects access to money or services, could disadvantage a language group, gives advice people may trust too strongly, or removes a necessary human review step.' },
    { id:'p3m1_b11', type:'application', variant:'SouthAfricanContext', content:'Suppose a school wants to reduce repeated parent questions about events. A responsible first prototype could use verified school notices to create a simple searchable FAQ with English plus locally relevant language support. It should avoid storing learner records, work on ordinary phones, keep critical dates visible offline, and direct unusual cases to a staff member.' },
    { id:'p3m1_b12', type:'activity', variant:'standard', content:'Choose one real problem from a school, TVET college, workplace, NGO, church, small business or community. Write: 1) one-sentence problem statement, 2) primary user, 3) current obstacle, 4) desired improvement, 5) whether AI is truly needed and why, 6) one task that must remain human, 7) one privacy, fairness or access risk, and 8) the smallest prototype you could test.' },
    { id:'p3m1_b13', type:'reflection', variant:'standard', content:'If the AI disappeared tomorrow, which part of your proposed solution would still be useful? If the answer is “nothing”, have you designed a solution around the technology rather than around the user?' },
    { id:'p3m1_b14', type:'summary', variant:'standard', content:'Responsible AI creation begins before any prompt or code is written. Define the real need, understand the user and context, verify the problem, choose the simplest appropriate approach, protect people from avoidable risk, then test a small solution and improve it from evidence.' },
  ],
  quiz: [
    { id:'p3m1_q1', question:'Which is the strongest starting point for an AI project?', options:['We want to use a chatbot.','A clearly defined user problem and desired improvement.','The newest AI model available.','A long list of possible features.'], correctIndex:1, explanation:'A responsible project begins with a real user problem and an outcome, not a preferred technology.' },
    { id:'p3m1_q2', question:'When should you choose a simpler non-AI solution?', options:['Never, because Level 3 is about AI.','When a checklist, form or other simple method solves the problem more reliably and cheaply.','Only when there is no internet anywhere.','Only when users ask for less technology.'], correctIndex:1, explanation:'AI is a means, not the goal. The simplest adequate solution is often the strongest design choice.' },
    { id:'p3m1_q3', question:'How should a builder verify that a problem is real?', options:['Assume the first idea is correct.','Ask AI whether the problem probably exists.','Use evidence such as user conversations, workflow observation and repeated requests.','Build the full product first and see what happens.'], correctIndex:2, explanation:'Real user evidence reduces the risk of building around assumptions.' },
    { id:'p3m1_q4', question:'Which issue most clearly requires a human responsibility checkpoint?', options:['Choosing an icon.','A system influencing whether someone receives an important service.','Changing a heading size.','Sorting a non-sensitive checklist alphabetically.'], correctIndex:1, explanation:'High-impact decisions about people require appropriate human authority, review and accountability.' },
    { id:'p3m1_q5', question:'What is the best first prototype for a new AI solution?', options:['The largest possible feature set.','A small version that tests the most important user need safely.','A version that collects as much user data as possible.','A desktop-only system even when users mainly have phones.'], correctIndex:1, explanation:'A small testable prototype reduces cost and risk and generates real evidence for the next design decision.' },
  ],
};
