import { Lesson } from './types';

export const levelThreeKnowledgeDataLesson: Lesson = {
  id: 'MZAIE-P3-M03-L01',
  title: 'Knowledge, Data & Source Design',
  levelId: 'MZAIE-P3',
  moduleId: 'MZAIE-P3-M03',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Choose trustworthy knowledge and data for an AI solution.',
    'Create a source hierarchy that tells the system which sources carry the most authority.',
    'Check freshness, provenance and local relevance before using information.',
    'Set clear boundaries for sensitive, private, uncertain or out-of-scope information.',
  ],
  competencyIds: ['DATA_AWARENESS', 'CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p3m3_b1', type:'objective', variant:'standard', content:'Design what an AI solution is allowed to know, which sources it should trust first, what it must reject, and how it should handle information that may be outdated or uncertain.' },
    { id:'p3m3_b2', type:'explanation', variant:'standard', content:'An AI solution is only as dependable as the knowledge and data it is given. Good source design reduces hallucinations, conflicting answers, outdated advice and accidental use of sensitive information.' },
    { id:'p3m3_b3', type:'keyPoint', variant:'standard', content:'Do not treat every source as equal. Build a source hierarchy so official, current and task-specific material outranks informal or secondary information.' },
    { id:'p3m3_b4', type:'application', variant:'plain', content:'Use the SOURCE MAP: Specify the information need. Order sources by authority. Understand who created each source and why. Record dates and versions. Check local relevance. Exclude unsafe or unnecessary data. Mark uncertainty. Assign a human review point.' },
    { id:'p3m3_b5', type:'example', variant:'SouthAfricanContext', content:'A TVET support assistant answering questions about a qualification should prioritise the current official curriculum or qualification documents used by the institution, then verified college guidance, and only then supplementary explanations. A social-media post or old PDF should never override the current official source.' },
    { id:'p3m3_b6', type:'explanation', variant:'standard', content:'Provenance means knowing where information came from. Record the organisation or author, document title, publication or review date, version where relevant, and whether the source is primary or secondary. If the origin cannot be established, lower the confidence placed in it.' },
    { id:'p3m3_b7', type:'keyPoint', variant:'standard', content:'Freshness is part of accuracy. Laws, fees, deadlines, policies, contact details, product information and eligibility rules can change. A trustworthy source can still be wrong for today if it is outdated.' },
    { id:'p3m3_b8', type:'example', variant:'SouthAfricanContext', content:'A bursary-information assistant should not simply store one old list of requirements. It should clearly separate stable guidance from changing items such as closing dates, funding amounts, contact details and eligibility rules, and require those changing fields to be checked against current official information.' },
    { id:'p3m3_b9', type:'ethicsCheck', variant:'standard', content:'Collect the minimum data required for the task. Do not place ID numbers, health records, private learner records, confidential case notes, passwords or unnecessary personal information into an AI knowledge base simply because the system can store it.' },
    { id:'p3m3_b10', type:'application', variant:'SouthAfricanContext', content:'Local relevance matters. A community service assistant may need English plus Afrikaans or isiXhosa wording, local office names, South African terminology and phone-friendly instructions. Generic global material should not silently replace verified local information.' },
    { id:'p3m3_b11', type:'verification', variant:'standard', content:'When two sources conflict, do not average them. Identify which source has the stronger authority, newer date and closer relationship to the claim. If the conflict cannot be resolved, the system should say that verification is needed rather than inventing certainty.' },
    { id:'p3m3_b12', type:'activity', variant:'standard', content:'Choose the prototype problem you defined in Level 3.1. Create a source map with: 1) five information needs, 2) the best source for each need, 3) source owner, 4) date or version, 5) primary or secondary status, 6) one local relevance check, 7) one item of data you will deliberately exclude, and 8) one claim that must always receive human verification.' },
    { id:'p3m3_b13', type:'reflection', variant:'standard', content:'If your AI gives a fluent answer but you cannot show where the information came from, how much should a user trust that answer?' },
    { id:'p3m3_b14', type:'summary', variant:'standard', content:'Responsible builders control the knowledge layer. Use authoritative and current sources, preserve provenance, design for local context, minimise personal data, mark uncertainty, and create clear human verification points for important claims.' },
  ],
  quiz: [
    { id:'p3m3_q1', question:'What is the main purpose of a source hierarchy?', options:['To make the source list longer.','To tell the system which sources should carry the most authority when information differs.','To remove all human review.','To make every source equally important.'], correctIndex:1, explanation:'A source hierarchy gives stronger, more authoritative sources priority over weaker or informal ones.' },
    { id:'p3m3_q2', question:'What does provenance help a builder understand?', options:['Where information came from and who produced it.','How bright the app screen should be.','How many users will install the app.','Whether a phone battery is full.'], correctIndex:0, explanation:'Provenance records the origin and context of information so its reliability can be evaluated.' },
    { id:'p3m3_q3', question:'Why must freshness be checked even for a trustworthy source?', options:['Because reliable sources can still contain information that has become outdated.','Because old documents always contain malware.','Because newer sources are automatically true.','Because dates are only useful for legal documents.'], correctIndex:0, explanation:'Rules, dates, prices, contact details and policies can change even when the original source was reliable.' },
    { id:'p3m3_q4', question:'Which information should usually be excluded from an ordinary AI knowledge base unless it is genuinely necessary and properly governed?', options:['Public opening hours.','A published course title.','Unnecessary ID numbers and confidential personal records.','A public government webpage.'], correctIndex:2, explanation:'Data minimisation reduces privacy and security risk by keeping unnecessary sensitive information out of the system.' },
    { id:'p3m3_q5', question:'What should an AI solution do when two important sources conflict and the conflict cannot be resolved?', options:['Choose whichever answer sounds more confident.','Combine the two claims into a new answer.','State that verification is needed and send the issue to human review.','Hide the conflict from the user.'], correctIndex:2, explanation:'Unresolved conflicts should be surfaced rather than converted into false certainty.' },
  ],
};
