import { Lesson } from './types';

export const levelTwoWritingLesson: Lesson = {
  id: 'MZAIE-P2-M02-L01',
  title: 'AI for Writing & Communication',
  levelId: 'MZAIE-P2',
  moduleId: 'MZAIE-P2-M02',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Use AI to plan, draft, improve and review everyday writing without losing your own voice.',
    'Match tone, audience and purpose across emails, reports, applications and presentations.',
    'Check AI-generated writing for accuracy, fairness, privacy risks and invented details.',
    'Use a repeatable writing workflow that keeps the human author responsible for the final message.',
  ],
  competencyIds: ['CRITICAL_QUESTIONING', 'RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    {
      id: 'p2m2_b1',
      type: 'objective',
      variant: 'standard',
      content: 'Learn to use AI as a writing assistant for planning, drafting and improving communication while keeping your purpose, facts, voice and responsibility in human hands.',
    },
    {
      id: 'p2m2_b2',
      type: 'explanation',
      variant: 'standard',
      content: 'Good writing begins before AI is involved. First decide who the reader is, what they need to know, what action you want them to take and what tone fits the situation. AI can then help organise ideas, suggest wording, shorten a draft, improve clarity or identify gaps.',
    },
    {
      id: 'p2m2_b3',
      type: 'keyPoint',
      variant: 'standard',
      content: 'AI should improve your communication, not erase your judgement or identity. A polished sentence is not automatically a truthful, appropriate or useful sentence.',
    },
    {
      id: 'p2m2_b4',
      type: 'application',
      variant: 'plain',
      content: 'Use the WRITE loop: Who is the reader? Result: what must the message achieve? Information: give only the relevant facts. Tone: choose the right level of formality. Edit: check every sentence, fact and claim before sending or submitting.',
    },
    {
      id: 'p2m2_b5',
      type: 'example',
      variant: 'SouthAfricanContext',
      content: 'A TVET learner applying for workplace experience could draft the facts first, then ask AI: “Context: I am a South African electrical engineering student applying for workplace exposure. Request: Help me improve this email. Examples: Keep my original facts and sound respectful but confident. Output: 150 words, subject line included.” The learner must check that the AI has not invented qualifications, dates or experience.',
    },
    {
      id: 'p2m2_b6',
      type: 'explanation',
      variant: 'standard',
      content: 'Different writing tasks need different tones. A WhatsApp message to a classmate can be brief and informal. An email to a principal, lecturer, employer or municipality usually needs a clear subject, greeting, purpose, relevant detail and respectful close. AI can help adjust tone, but the writer decides what is appropriate.',
    },
    {
      id: 'p2m2_b7',
      type: 'example',
      variant: 'SouthAfricanContext',
      content: 'A community organisation preparing a short funding update could use AI to turn rough bullet points into a clear draft. Before sending it, a human should confirm the beneficiary numbers, dates, amounts, project outcomes and any claims about the community. AI must never create evidence that does not exist.',
    },
    {
      id: 'p2m2_b8',
      type: 'verification',
      variant: 'standard',
      content: 'Check names, dates, contact details, statistics, quotations, legal claims, qualifications and references. If the writing depends on a fact, verify the fact from the original or trusted source rather than trusting the AI wording.',
    },
    {
      id: 'p2m2_b9',
      type: 'ethicsCheck',
      variant: 'standard',
      content: 'Do not paste confidential work emails, private learner records, ID numbers, disciplinary information, medical details or another person’s private messages into an AI service unless you are authorised and the service is appropriate for that information. Remove unnecessary personal details.',
    },
    {
      id: 'p2m2_b10',
      type: 'application',
      variant: 'SouthAfricanContext',
      content: 'AI can help with language support. A learner may draft an idea in familiar language, ask for a clear English version, or ask for difficult wording to be simplified. But meaning can shift during translation or rewriting, so names, technical terms, instructions and culturally important expressions should be checked carefully.',
    },
    {
      id: 'p2m2_b11',
      type: 'activity',
      variant: 'standard',
      content: 'Choose one real, non-sensitive message you need to write. Draft it yourself in rough form. Then use the WRITE loop to ask AI for one improved version. Compare the two drafts and mark three changes you accept and one change you reject. Rewrite the final message in your own voice.',
    },
    {
      id: 'p2m2_b12',
      type: 'reflection',
      variant: 'standard',
      content: 'If a message sounds professional but no longer sounds like you, is that always an improvement? What parts of your own voice, culture or relationship with the reader should remain visible?',
    },
    {
      id: 'p2m2_b13',
      type: 'keyPoint',
      variant: 'standard',
      content: 'The human author owns the final communication. Before you send, submit or publish, ask: Is it true? Is it appropriate for this reader? Is private information protected? Does it still express what I actually mean?',
    },
    {
      id: 'p2m2_b14',
      type: 'summary',
      variant: 'standard',
      content: 'Use AI to plan, clarify, restructure and improve writing. Start with your purpose and facts, give the AI enough context, protect private information, check all important claims and make the final wording your responsibility.',
    },
  ],
  quiz: [
    {
      id: 'p2m2_q1',
      question: 'What should you decide before asking AI to improve an important message?',
      options: [
        'Only which AI model is most popular.',
        'The reader, purpose, key information and suitable tone.',
        'How long the AI answer can be.',
        'How to make the message sound as complicated as possible.',
      ],
      correctIndex: 1,
      explanation: 'Audience, purpose, facts and tone guide good communication and give the AI a clear task.',
    },
    {
      id: 'p2m2_q2',
      question: 'What is the safest response if AI adds work experience you never had to a job application?',
      options: [
        'Keep it because it sounds impressive.',
        'Send it quickly before anyone checks.',
        'Remove the invented claim and correct the draft using your real information.',
        'Ask AI to invent a reference as well.',
      ],
      correctIndex: 2,
      explanation: 'AI-generated writing must not invent qualifications, experience or evidence. The final document must remain truthful.',
    },
    {
      id: 'p2m2_q3',
      question: 'Which is the best use of AI for a formal email?',
      options: [
        'Ask AI to decide the facts for you.',
        'Use AI to improve structure and tone, then verify and edit the final message yourself.',
        'Paste confidential information so the AI has every possible detail.',
        'Send the first AI draft without reading it.',
      ],
      correctIndex: 1,
      explanation: 'AI can support structure and wording, but the human author must verify facts, privacy and appropriateness before sending.',
    },
    {
      id: 'p2m2_q4',
      question: 'Why should translated or rewritten AI text still be checked?',
      options: [
        'Because AI can change meaning, terminology or tone during rewriting.',
        'Because translated text is always illegal.',
        'Because AI cannot work with any language except English.',
        'Because every sentence must contain technical words.',
      ],
      correctIndex: 0,
      explanation: 'Rewriting and translation can alter meaning or important terminology, so the final version needs human checking.',
    },
    {
      id: 'p2m2_q5',
      question: 'Who is responsible for the final message after AI has helped draft it?',
      options: [
        'The AI system only.',
        'The person who sends, submits or publishes the message.',
        'Nobody, because AI was involved.',
        'The internet provider.',
      ],
      correctIndex: 1,
      explanation: 'The human author remains responsible for the truth, privacy, tone and final decision to use the communication.',
    },
  ],
};
