import { Lesson } from './types';

export const levelThreeNoCodeLowCodeLesson: Lesson = {
  id: 'MZAIE-P3-M04-L01',
  title: 'Building with No-Code & Low-Code AI',
  levelId: 'MZAIE-P3',
  moduleId: 'MZAIE-P3-M04',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Explain the difference between no-code, low-code and full-code approaches.',
    'Choose the simplest practical build approach for a small AI prototype.',
    'Assemble a small prototype from clear inputs, rules, prompts, outputs and human checks.',
    'Design for mobile access, low data use, failure recovery and responsible testing.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p3m4_b1', type:'objective', variant:'standard', content:'Turn a Level 3 design into a small working prototype without over-engineering it. Use the simplest tools that can test the real user need safely.' },
    { id:'p3m4_b2', type:'explanation', variant:'standard', content:'No-code tools let you build with visual screens, forms, rules and ready-made services. Low-code tools add small amounts of code or configuration when needed. Full-code development gives the most control, but it also adds complexity, cost and maintenance. The best choice depends on the problem, not on which option sounds most advanced.' },
    { id:'p3m4_b3', type:'keyPoint', variant:'standard', content:'Build the smallest useful version first. A prototype only needs enough functionality to test whether the solution helps the intended user.' },
    { id:'p3m4_b4', type:'application', variant:'plain', content:'Use the BUILD loop: Break the solution into one essential user task. Use the simplest available tool. Identify the input. Link the processing step or prompt. Define the output. Add a human check. Limit data collection. Decide what happens when the internet, AI service or input fails.' },
    { id:'p3m4_b5', type:'example', variant:'SouthAfricanContext', content:'A community training centre wants learners to turn difficult course notes into plain-language revision questions. A first prototype could use a simple mobile form where the learner pastes non-sensitive notes, selects “plain explanation” or “practice questions”, and receives a structured result. The prototype does not need accounts, analytics, payments or a complex dashboard to test whether the core idea helps.' },
    { id:'p3m4_b6', type:'explanation', variant:'standard', content:'Think of a prototype as five connected parts: INPUT, what the user provides. RULE or PROMPT, what the system should do. PROCESS, the tool or AI service that performs the task. OUTPUT, what the user receives. CHECK, the point where a person reviews, corrects or decides what happens next.' },
    { id:'p3m4_b7', type:'keyPoint', variant:'standard', content:'Do not collect information simply because a tool allows it. Every field, upload and stored value should have a clear reason connected to the user task.' },
    { id:'p3m4_b8', type:'example', variant:'SouthAfricanContext', content:'A small NGO wants a volunteer notice generator. Instead of storing volunteer identity numbers, home addresses and personal profiles, the prototype may only need the event type, date, meeting place, audience and preferred language. Data minimisation makes the tool easier and safer.' },
    { id:'p3m4_b9', type:'verification', variant:'standard', content:'Test each connection in the prototype separately. Does the input accept the right information? Does the prompt follow the intended rules? Does the output stay within the required format? Does the human checkpoint appear before a high-impact action? A working screen does not prove the workflow is correct.' },
    { id:'p3m4_b10', type:'ethicsCheck', variant:'standard', content:'Before connecting an AI service, check what information would leave the device, whether the service requires an account, whether user content may be stored, and whether the task can still function safely when the service is unavailable. Avoid sending sensitive personal data into public AI tools unless there is an authorised, appropriate and protected process.' },
    { id:'p3m4_b11', type:'application', variant:'SouthAfricanContext', content:'Design for ordinary phones and unstable connectivity. Keep screens simple, avoid large downloads, minimise repeated network calls, preserve useful local instructions, and provide a clear fallback when connected AI is unavailable. A prototype that only works on fast Wi-Fi may fail the people it was meant to serve.' },
    { id:'p3m4_b12', type:'activity', variant:'standard', content:'Take the solution you designed in Modules 3.1 to 3.3. Write a one-page prototype plan with: 1) one essential user task, 2) input, 3) rule or prompt, 4) processing step, 5) output, 6) human checkpoint, 7) information that will not be collected, 8) offline or service-failure fallback, and 9) the simplest no-code, low-code or coded approach you would test first.' },
    { id:'p3m4_b13', type:'reflection', variant:'standard', content:'Which feature are you most tempted to add even though it is not necessary to test the main user need? What would happen if you deliberately removed it from version one?' },
    { id:'p3m4_b14', type:'summary', variant:'standard', content:'Good builders do not confuse complexity with quality. Choose the simplest suitable build method, connect only the essential workflow parts, minimise data, include human checks, design for real device and connectivity conditions, test a small prototype, then improve from evidence.' },
  ],
  quiz: [
    { id:'p3m4_q1', question:'What is the strongest reason to choose a no-code or low-code approach?', options:['It always produces better AI.','It can test a useful solution quickly when the required control and complexity are modest.','It removes the need for human testing.','It guarantees the system will work offline.'], correctIndex:1, explanation:'No-code and low-code approaches are useful when they provide enough capability to test the user need without unnecessary engineering.' },
    { id:'p3m4_q2', question:'Which set best describes the core parts of a small AI prototype?', options:['Logo, subscription, analytics, advertisements, social sharing.','Input, rule or prompt, processing, output and human check.','Database, payment gateway, marketing page, password reset and reports.','Training data, GPU, code repository, investor deck and API key.'], correctIndex:1, explanation:'A small prototype can often be understood as an input, instruction or rule, processing step, output and human checkpoint.' },
    { id:'p3m4_q3', question:'What does data minimisation mean in a prototype?', options:['Collect as much data as possible and delete it later.','Collect only information that is genuinely needed for the user task.','Store all inputs locally forever.','Avoid all user input.'], correctIndex:1, explanation:'Data minimisation reduces risk by limiting collection to information needed for the intended function.' },
    { id:'p3m4_q4', question:'What should happen if a connected AI service is unavailable?', options:['The app should fail silently.','The user should lose all previously available guidance.','The design should provide a clear fallback or explain what remains available.','The prototype should automatically collect more data.'], correctIndex:2, explanation:'A resilient design makes failure visible and preserves useful fallback behaviour where possible.' },
    { id:'p3m4_q5', question:'Which is the best version-one prototype?', options:['The one with the most features.','The smallest version that safely tests the main user need.','The one using the newest platform.','The one that requires the fastest device.'], correctIndex:1, explanation:'Version one should generate evidence about the core user need with the least unnecessary complexity and risk.' },
  ],
};
