import { Lesson } from './types';

export const levelFourSmallBusinessEntrepreneurshipLesson: Lesson = {
  id: 'MZAIE-P4-M04-L01',
  title: 'Small Business & Entrepreneurship',
  levelId: 'MZAIE-P4',
  moduleId: 'MZAIE-P4-M04',
  locale: 'en-ZA',
  version: '1.0',
  estimatedMinutes: 20,
  objectives: [
    'Identify practical small-business workflows where AI can save time without replacing owner judgement.',
    'Use AI to support planning, customer communication and administration with clear human review.',
    'Reduce privacy, accuracy and reputation risks when using AI in a small enterprise.',
    'Test whether an AI-supported business workflow produces a useful result for real customers or users.',
  ],
  competencyIds: ['RESPONSIBLE_AI_USE', 'HUMAN_JUDGEMENT', 'BASIC_PRIVACY', 'CRITICAL_QUESTIONING', 'UBUNTU_TECHNOLOGY_AWARENESS'],
  activityIds: [],
  assessmentId: null,
  sourceIds: [],
  offlineEligible: true,
  trustState: 'AI_ASSISTED_REVIEWED',
  blocks: [
    { id:'p4m4_b1', type:'objective', variant:'standard', content:'Use AI as a practical support tool for small-business work such as planning, communication, stock thinking, customer service, simple admin and opportunity discovery while keeping the owner responsible for decisions.' },
    { id:'p4m4_b2', type:'explanation', variant:'standard', content:'Small businesses often work with limited time, cash flow, staff, data and digital skills. AI can help organise thinking and draft useful material, but it can also invent facts, overpromise to customers or expose private business information if used carelessly.' },
    { id:'p4m4_b3', type:'keyPoint', variant:'standard', content:'A good business AI workflow saves time on repeated tasks. It does not remove the owner’s responsibility to check prices, promises, dates, customer details, legal requirements or financial decisions.' },
    { id:'p4m4_b4', type:'application', variant:'plain', content:'Use the TRADE workflow: Task to improve. Real customer need. Accurate inputs. Draft or plan with AI. Edit with human judgement. Test the result. This keeps the tool practical and accountable.' },
    { id:'p4m4_b5', type:'example', variant:'SouthAfricanContext', content:'A township food seller wants clearer WhatsApp messages for daily specials. AI can draft short messages in plain language and help plan weekly themes. The owner still checks prices, stock, delivery area and whether the wording matches the business voice.' },
    { id:'p4m4_b6', type:'explanation', variant:'standard', content:'Useful small-business AI tasks include drafting customer replies, summarising feedback, creating checklists, preparing simple product descriptions, comparing options, planning social posts and turning rough notes into a clearer action list.' },
    { id:'p4m4_b7', type:'keyPoint', variant:'standard', content:'Never put unnecessary customer information, private financial details, passwords, banking information or sensitive staff matters into an AI tool. If the business would not place the information on a public counter, treat it with care.' },
    { id:'p4m4_b8', type:'example', variant:'SouthAfricanContext', content:'A small repair business wants a quote template. AI can help draft a polite structure, but the owner must check labour, parts, transport, VAT status, warranty wording and what happens if extra faults are found.' },
    { id:'p4m4_b9', type:'verification', variant:'standard', content:'Before using an AI-supported business workflow with customers, test it on three sample cases. Check whether the answer is accurate, clear, affordable to deliver and honest about what the business can actually do.' },
    { id:'p4m4_b10', type:'ethicsCheck', variant:'standard', content:'Ask whether the AI output could mislead customers, hide important conditions, treat people unfairly, create unaffordable promises, expose personal information or make the business look more capable than it really is.' },
    { id:'p4m4_b11', type:'application', variant:'SouthAfricanContext', content:'For a spaza, salon, mechanic, tutor or community service, start with one narrow workflow: customer enquiry response, appointment reminder, product list cleanup, weekly planning or FAQ sheet. Keep it offline-friendly where possible and avoid complex systems before the workflow proves useful.' },
    { id:'p4m4_b12', type:'activity', variant:'standard', content:'Choose one small-business task. Write: 1) the repeated task, 2) who benefits, 3) the information AI may use, 4) the information AI must not use, 5) the human review step, 6) one possible customer risk, 7) one small test, and 8) how you will measure whether it saved time or improved service.' },
    { id:'p4m4_b13', type:'reflection', variant:'standard', content:'Would this AI workflow make the business more trustworthy, or only faster? What must the owner still personally check?' },
    { id:'p4m4_b14', type:'summary', variant:'standard', content:'AI can help small businesses with repeated communication, planning and admin tasks when the workflow is narrow, accurate, privacy-aware and checked by a responsible person. The goal is better service and clearer decisions, not careless automation.' },
  ],
  quiz: [
    { id:'p4m4_q1', question:'What is the best role for AI in a small business?', options:['Make final decisions without the owner.','Support repeated tasks while the owner checks accuracy and promises.','Collect customer information without limits.','Replace customer trust with automation.'], correctIndex:1, explanation:'AI can save time, but the owner remains responsible for accuracy, promises and judgement.' },
    { id:'p4m4_q2', question:'Which information should not be entered into an AI tool unnecessarily?', options:['A public product description.','A general planning idea.','Customer private details, banking information or passwords.','A rough social media post idea.'], correctIndex:2, explanation:'Sensitive personal, financial or security information should be protected.' },
    { id:'p4m4_q3', question:'Why should AI-generated quotes or customer messages be reviewed?', options:['Because AI may invent facts, prices, promises or conditions.','Because review makes the message longer.','Because customers do not read messages.','Because all AI output is legally approved.'], correctIndex:0, explanation:'Business communication affects trust, cost and delivery, so it must be checked.' },
    { id:'p4m4_q4', question:'What is the strongest way to start using AI in a small business?', options:['Automate everything at once.','Choose one narrow repeated workflow and test it on sample cases.','Use AI only for private financial decisions.','Remove all human checks.'], correctIndex:1, explanation:'A narrow tested workflow is safer and more useful than broad automation.' },
    { id:'p4m4_q5', question:'What should a useful business AI workflow improve?', options:['Speed only, even if customers are misled.','Service, clarity, time use or planning while protecting trust and accountability.','The amount of private data collected.','The number of promises made to customers.'], correctIndex:1, explanation:'The workflow should improve real business outcomes without weakening trust or accountability.' },
  ],
};
